// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Laboratorios_Univalle.Data;

#nullable disable

namespace Proyecto_Laboratorios_Univalle.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251220153709_FixSolicitudSolicitadoPor")]
    partial class FixSolicitudSolicitadoPor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.DetalleCosto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdMantenimiento")
                        .HasColumnType("int");

                    b.Property<string>("NumeroFactura")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RegistradoPorId")
                        .HasColumnType("int");

                    b.Property<string>("UnidadMedida")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdMantenimiento");

                    b.HasIndex("RegistradoPorId");

                    b.ToTable("DetallesCostos");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Equipamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CiudadId")
                        .HasColumnType("int");

                    b.Property<int?>("CreadoPorId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("FechaAdquisicion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdLaboratorio")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoEquipamiento")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NroInventario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<string>("Serie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ValorAdquisicion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VidaUtilAnios")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CiudadId");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("IdLaboratorio");

                    b.HasIndex("IdTipoEquipamiento");

                    b.HasIndex("ModificadoPorId");

                    b.HasIndex("NroInventario")
                        .IsUnique();

                    b.HasIndex("PaisId");

                    b.ToTable("Equipamientos");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.EstadoEquipamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RegistradoPorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdEquipo");

                    b.HasIndex("RegistradoPorId");

                    b.ToTable("EstadosEquipamiento");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Facultad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Facultades");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Laboratorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Edificio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdFacultad")
                        .HasColumnType("int");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Piso")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UltimaModificacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("IdFacultad");

                    b.HasIndex("ModificadoPorId");

                    b.HasIndex("Siglas")
                        .IsUnique();

                    b.ToTable("Laboratorios");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Mantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AprobadoPorId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostoEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostoReal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CreadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaIniciada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaProgramada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSugeridaProximoMtto")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaTerminada")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("int");

                    b.Property<int?>("IdSolicitud")
                        .HasColumnType("int");

                    b.Property<int?>("IdTecnico")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoMantenimiento")
                        .HasColumnType("int");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Recomendaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ServicioEfectuadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UltimaModificacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AprobadoPorId");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("IdEquipo");

                    b.HasIndex("IdSolicitud")
                        .IsUnique()
                        .HasFilter("[IdSolicitud] IS NOT NULL");

                    b.HasIndex("IdTecnico");

                    b.HasIndex("IdTipoMantenimiento");

                    b.HasIndex("ModificadoPorId");

                    b.ToTable("Mantenimientos");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.PlanMantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BloqueSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("int");

                    b.Property<int?>("IdUserTecnico")
                        .HasColumnType("int");

                    b.Property<int?>("LaboratorioId")
                        .HasColumnType("int");

                    b.Property<string>("LaboratorioSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("TiempoEstimado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("TiempoReal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TipoServicio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdEquipo");

                    b.HasIndex("IdUserTecnico");

                    b.HasIndex("LaboratorioId");

                    b.ToTable("PlanesMantenimiento");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AprobadoPorId")
                        .HasColumnType("int");

                    b.Property<int?>("CreadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("int");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Prioridad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SolicitadoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AprobadoPorId");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("IdEquipo");

                    b.HasIndex("ModificadoPorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.TipoEquipamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("FrecuenciaMantenimientoMeses")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequiereCalibracion")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TiposEquipamiento");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.TipoMantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TiposMantenimiento");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("CreadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UltimaModificacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CI")
                        .IsUnique();

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("ModificadoPorId");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Verificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AprobadoPorId")
                        .HasColumnType("int");

                    b.Property<int?>("CreadoPorId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("HallazgosCriticos")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("int");

                    b.Property<int?>("IdMantenimiento")
                        .HasColumnType("int");

                    b.Property<int?>("IdTecnico")
                        .HasColumnType("int");

                    b.Property<bool>("InspeccionEncendidoHorno")
                        .HasColumnType("bit");

                    b.Property<bool>("InspeccionIntercambiadorCalor")
                        .HasColumnType("bit");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Recomendaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("RevisionEncendedorElectrodo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("VerificacionAjusteElectrovalvula")
                        .HasColumnType("bit");

                    b.Property<bool>("VerificacionAlarmasSonoras")
                        .HasColumnType("bit");

                    b.Property<bool>("VerificacionCableado")
                        .HasColumnType("bit");

                    b.Property<bool>("VerificacionLimpiezaExterna")
                        .HasColumnType("bit");

                    b.Property<bool>("VerificacionLimpiezaInterna")
                        .HasColumnType("bit");

                    b.Property<bool>("VerificacionLlamaCombustion")
                        .HasColumnType("bit");

                    b.Property<bool>("VerificacionLubricacion")
                        .HasColumnType("bit");

                    b.Property<bool>("VerificacionLuminarias")
                        .HasColumnType("bit");

                    b.Property<bool>("VerificacionMangueraAgua")
                        .HasColumnType("bit");

                    b.Property<bool>("VerificacionMangueraGas")
                        .HasColumnType("bit");

                    b.Property<bool>("VerificacionPantallaLED")
                        .HasColumnType("bit");

                    b.Property<bool>("VerificacionPosicionamientoTermocupla")
                        .HasColumnType("bit");

                    b.Property<bool>("VerificacionQuemador")
                        .HasColumnType("bit");

                    b.Property<bool>("VerificacionSalidaVapor")
                        .HasColumnType("bit");

                    b.Property<bool>("VerificacionSensorLlama")
                        .HasColumnType("bit");

                    b.Property<bool>("VerificacionTemperatura")
                        .HasColumnType("bit");

                    b.Property<bool>("VerificacionVaporAltaTemp")
                        .HasColumnType("bit");

                    b.Property<bool>("VerificacionVentilador")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AprobadoPorId");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("IdEquipo");

                    b.HasIndex("IdMantenimiento");

                    b.HasIndex("IdTecnico");

                    b.HasIndex("ModificadoPorId");

                    b.ToTable("Verificaciones");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Ciudad", b =>
                {
                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Pais", "Pais")
                        .WithMany("Ciudades")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.DetalleCosto", b =>
                {
                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Mantenimiento", "Mantenimiento")
                        .WithMany("DetallesCostos")
                        .HasForeignKey("IdMantenimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Mantenimiento");

                    b.Navigation("RegistradoPor");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Equipamiento", b =>
                {
                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Ciudad", "Ciudad")
                        .WithMany("Equipamientos")
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Laboratorio", "Laboratorio")
                        .WithMany("Equipamientos")
                        .HasForeignKey("IdLaboratorio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.TipoEquipamiento", "TipoEquipamiento")
                        .WithMany("Equipamientos")
                        .HasForeignKey("IdTipoEquipamiento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Usuario", "ModificadoPor")
                        .WithMany()
                        .HasForeignKey("ModificadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Pais", "Pais")
                        .WithMany("Equipamientos")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ciudad");

                    b.Navigation("CreadoPor");

                    b.Navigation("Laboratorio");

                    b.Navigation("ModificadoPor");

                    b.Navigation("Pais");

                    b.Navigation("TipoEquipamiento");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.EstadoEquipamiento", b =>
                {
                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Equipamiento", "Equipamiento")
                        .WithMany("EstadosEquipamiento")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Equipamiento");

                    b.Navigation("RegistradoPor");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Laboratorio", b =>
                {
                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Facultad", "Facultad")
                        .WithMany("Laboratorios")
                        .HasForeignKey("IdFacultad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Usuario", "ModificadoPor")
                        .WithMany()
                        .HasForeignKey("ModificadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreadoPor");

                    b.Navigation("Facultad");

                    b.Navigation("ModificadoPor");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Mantenimiento", b =>
                {
                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Usuario", "AprobadoPor")
                        .WithMany()
                        .HasForeignKey("AprobadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Equipamiento", "Equipamiento")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Solicitud", "Solicitud")
                        .WithOne("Mantenimiento")
                        .HasForeignKey("Proyecto_Laboratorios_Univalle.Models.Mantenimiento", "IdSolicitud")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Usuario", "Tecnico")
                        .WithMany("MantenimientosRealizados")
                        .HasForeignKey("IdTecnico")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.TipoMantenimiento", "TipoMantenimiento")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("IdTipoMantenimiento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Usuario", "ModificadoPor")
                        .WithMany()
                        .HasForeignKey("ModificadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AprobadoPor");

                    b.Navigation("CreadoPor");

                    b.Navigation("Equipamiento");

                    b.Navigation("ModificadoPor");

                    b.Navigation("Solicitud");

                    b.Navigation("Tecnico");

                    b.Navigation("TipoMantenimiento");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.PlanMantenimiento", b =>
                {
                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Equipamiento", "Equipamiento")
                        .WithMany("PlanesMantenimiento")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Usuario", "UsuarioTecnico")
                        .WithMany("PlanesAsignados")
                        .HasForeignKey("IdUserTecnico")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Laboratorio", null)
                        .WithMany("PlanesMantenimiento")
                        .HasForeignKey("LaboratorioId");

                    b.Navigation("Equipamiento");

                    b.Navigation("UsuarioTecnico");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Solicitud", b =>
                {
                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Usuario", "AprobadoPor")
                        .WithMany()
                        .HasForeignKey("AprobadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Equipamiento", "Equipamiento")
                        .WithMany()
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Usuario", "ModificadoPor")
                        .WithMany()
                        .HasForeignKey("ModificadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Usuario", null)
                        .WithMany("SolicitudesCreadas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("AprobadoPor");

                    b.Navigation("CreadoPor");

                    b.Navigation("Equipamiento");

                    b.Navigation("ModificadoPor");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Usuario", b =>
                {
                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Usuario", "ModificadoPor")
                        .WithMany()
                        .HasForeignKey("ModificadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreadoPor");

                    b.Navigation("ModificadoPor");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Verificacion", b =>
                {
                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Usuario", "AprobadoPor")
                        .WithMany()
                        .HasForeignKey("AprobadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Equipamiento", "Equipamiento")
                        .WithMany("Verificaciones")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Mantenimiento", "Mantenimiento")
                        .WithMany()
                        .HasForeignKey("IdMantenimiento")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Usuario", "Tecnico")
                        .WithMany()
                        .HasForeignKey("IdTecnico")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto_Laboratorios_Univalle.Models.Usuario", "ModificadoPor")
                        .WithMany()
                        .HasForeignKey("ModificadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AprobadoPor");

                    b.Navigation("CreadoPor");

                    b.Navigation("Equipamiento");

                    b.Navigation("Mantenimiento");

                    b.Navigation("ModificadoPor");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Ciudad", b =>
                {
                    b.Navigation("Equipamientos");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Equipamiento", b =>
                {
                    b.Navigation("EstadosEquipamiento");

                    b.Navigation("Mantenimientos");

                    b.Navigation("PlanesMantenimiento");

                    b.Navigation("Verificaciones");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Facultad", b =>
                {
                    b.Navigation("Laboratorios");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Laboratorio", b =>
                {
                    b.Navigation("Equipamientos");

                    b.Navigation("PlanesMantenimiento");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Mantenimiento", b =>
                {
                    b.Navigation("DetallesCostos");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Pais", b =>
                {
                    b.Navigation("Ciudades");

                    b.Navigation("Equipamientos");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Solicitud", b =>
                {
                    b.Navigation("Mantenimiento");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.TipoEquipamiento", b =>
                {
                    b.Navigation("Equipamientos");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.TipoMantenimiento", b =>
                {
                    b.Navigation("Mantenimientos");
                });

            modelBuilder.Entity("Proyecto_Laboratorios_Univalle.Models.Usuario", b =>
                {
                    b.Navigation("MantenimientosRealizados");

                    b.Navigation("PlanesAsignados");

                    b.Navigation("SolicitudesCreadas");
                });
#pragma warning restore 612, 618
        }
    }
}
