BEGIN;

-- MIG-F1-PG-DASHBOARD-001
-- First additive tenant slice. The tenant database owns operational rows; the
-- control plane owns users, sites, faculties and careers. site_id is retained
-- on every row as a defence-in-depth isolation key and is never supplied by
-- the browser.
SELECT pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext('lu:tenant:dashboard:0001')
);

CREATE TABLE IF NOT EXISTS public.lu_management (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    year integer NOT NULL,
    semester integer NOT NULL,
    code varchar(50) NOT NULL,
    description varchar(1000),
    start_date date,
    planned_end_date date,
    actual_closed_date date,
    status integer NOT NULL DEFAULT 0,
    responsible varchar(200),
    type integer NOT NULL DEFAULT 0,
    faculty_id bigint,
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz,
    row_version bigint NOT NULL DEFAULT 0,
    CONSTRAINT ck_lu_management_year CHECK (year BETWEEN 2000 AND 2100),
    CONSTRAINT ck_lu_management_semester CHECK (semester BETWEEN 0 AND 2),
    CONSTRAINT ck_lu_management_status CHECK (status IN (0, 1, 2, 99)),
    CONSTRAINT ck_lu_management_type CHECK (type IN (0, 1))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_lu_management_site_code
    ON public.lu_management (site_id, lower(code));
CREATE UNIQUE INDEX IF NOT EXISTS ux_lu_management_active_type
    ON public.lu_management (site_id, type) WHERE status = 0;

CREATE TABLE IF NOT EXISTS public.lu_laboratory (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    faculty_id bigint NOT NULL,
    code varchar(20) NOT NULL,
    name varchar(200) NOT NULL,
    type varchar(100),
    building varchar(100),
    block varchar(50),
    floor varchar(50),
    room varchar(100),
    description varchar(1000),
    status integer NOT NULL DEFAULT 0,
    city_id bigint,
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz,
    CONSTRAINT ck_lu_laboratory_status CHECK (status IN (0, 1, 2))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_lu_laboratory_site_code
    ON public.lu_laboratory (site_id, lower(code));

CREATE TABLE IF NOT EXISTS public.lu_equipment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    category integer NOT NULL DEFAULT 0,
    utensil_type integer,
    type_classification varchar(200),
    classification_review_status integer NOT NULL DEFAULT 0,
    other_classification_detail varchar(1000),
    status integer NOT NULL DEFAULT 0,
    catalog_code varchar(30),
    image_url varchar(2000),
    country_id bigint,
    city_id bigint,
    name varchar(200) NOT NULL,
    brand varchar(100),
    model varchar(100),
    useful_life_years integer,
    description varchar(2000),
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz,
    row_version bigint NOT NULL DEFAULT 0,
    CONSTRAINT ck_lu_equipment_category CHECK (category IN (0, 1, 2)),
    CONSTRAINT ck_lu_equipment_status CHECK (status IN (0, 1, 2)),
    CONSTRAINT ck_lu_equipment_life CHECK (useful_life_years IS NULL OR useful_life_years BETWEEN 0 AND 100)
);

CREATE INDEX IF NOT EXISTS ix_lu_equipment_site_name
    ON public.lu_equipment (site_id, lower(name));

CREATE TABLE IF NOT EXISTS public.lu_equipment_unit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    management_id bigint,
    equipment_id bigint NOT NULL,
    laboratory_id bigint,
    location_resolution_status integer NOT NULL DEFAULT 0,
    inventory_number varchar(50) NOT NULL,
    serial_number varchar(100),
    career_id bigint,
    internal_location varchar(200),
    acquisition_date date,
    manufacturing_date date,
    acquisition_value numeric(18,2),
    current_status integer NOT NULL DEFAULT 0,
    physical_condition integer,
    notes varchar(2000),
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz,
    row_version bigint NOT NULL DEFAULT 0,
    CONSTRAINT ck_lu_equipment_unit_value CHECK (acquisition_value IS NULL OR acquisition_value >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_lu_equipment_unit_site_inventory
    ON public.lu_equipment_unit (site_id, lower(inventory_number));
CREATE INDEX IF NOT EXISTS ix_lu_equipment_unit_site_lab
    ON public.lu_equipment_unit (site_id, laboratory_id);

CREATE TABLE IF NOT EXISTS public.lu_management_plan (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    management_id bigint NOT NULL,
    maintenance_id bigint,
    equipment_unit_id bigint,
    verification_id bigint,
    request_id bigint,
    departure_id bigint,
    kardex_history_id bigint,
    acquisition_request_id bigint,
    current_phase integer NOT NULL DEFAULT 1,
    current_state integer NOT NULL DEFAULT 1,
    responsible varchar(200),
    responsible_person_id bigint,
    planned_week integer,
    executed_week integer,
    document_reference varchar(500),
    notes varchar(1000),
    planned_date timestamptz,
    plan_status integer NOT NULL DEFAULT 0,
    is_draft boolean NOT NULL DEFAULT false,
    draft_phase integer,
    draft_saved_at timestamptz,
    draft_summary varchar(300),
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz,
    row_version bigint NOT NULL DEFAULT 0,
    CONSTRAINT ck_lu_management_plan_phase CHECK (current_phase BETWEEN 1 AND 6),
    CONSTRAINT ck_lu_management_plan_state CHECK (current_state BETWEEN 1 AND 9),
    CONSTRAINT ck_lu_management_plan_status CHECK (plan_status IN (0, 1, 2, 3)),
    CONSTRAINT ck_lu_management_plan_weeks CHECK (
        (planned_week IS NULL OR planned_week BETWEEN 1 AND 8)
        AND (executed_week IS NULL OR executed_week BETWEEN 1 AND 8)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_lu_management_plan_site_management_unit
    ON public.lu_management_plan (site_id, management_id, equipment_unit_id)
    WHERE equipment_unit_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_lu_management_plan_site_management_phase
    ON public.lu_management_plan (site_id, management_id, current_phase, current_state);

CREATE TABLE IF NOT EXISTS public.lu_notification (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    user_id uuid,
    title varchar(100) NOT NULL,
    message varchar(255) NOT NULL,
    action_url varchar(255),
    icon_class varchar(50),
    management_id bigint,
    management_type integer,
    scope varchar(50),
    is_read boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_lu_notification_type CHECK (management_type IS NULL OR management_type IN (0, 1))
);

CREATE INDEX IF NOT EXISTS ix_lu_notification_site_unread
    ON public.lu_notification (site_id, is_read, created_at DESC);

DO $grant$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'lu_auth_runtime') THEN
        GRANT USAGE ON SCHEMA public TO lu_auth_runtime;
        GRANT SELECT ON TABLE public.lu_management, public.lu_laboratory,
            public.lu_equipment, public.lu_equipment_unit,
            public.lu_management_plan, public.lu_notification TO lu_auth_runtime;
        GRANT UPDATE (is_read) ON public.lu_notification TO lu_auth_runtime;
    END IF;
END
$grant$;

COMMIT;
