BEGIN;

-- MIG-F2-PG-CATALOGS-001
-- Operational catalogues are tenant-local. Cross-database control-plane joins
-- are deliberately avoided; audit ids remain opaque control-plane UUIDs.
SELECT pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext('lu:tenant:catalogs:0002')
);

CREATE TABLE IF NOT EXISTS public.lu_country (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    name varchar(100) NOT NULL,
    status integer NOT NULL DEFAULT 0,
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz,
    CONSTRAINT ck_lu_country_status CHECK (status IN (0, 1, 2)),
    CONSTRAINT ux_lu_country_site_id UNIQUE (site_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_lu_country_site_name_active
    ON public.lu_country (site_id, lower(name))
    WHERE status <> 2;

CREATE TABLE IF NOT EXISTS public.lu_city (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    country_id bigint NOT NULL,
    name varchar(100) NOT NULL,
    region varchar(100),
    status integer NOT NULL DEFAULT 0,
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz,
    CONSTRAINT ck_lu_city_status CHECK (status IN (0, 1, 2)),
    CONSTRAINT fk_lu_city_country_site
        FOREIGN KEY (site_id, country_id)
        REFERENCES public.lu_country (site_id, id)
        ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_lu_city_site_country_name_active
    ON public.lu_city (site_id, country_id, lower(name))
    WHERE status <> 2;
CREATE INDEX IF NOT EXISTS ix_lu_city_site_country
    ON public.lu_city (site_id, country_id, lower(name));

DO $grant$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'lu_auth_runtime') THEN
        GRANT USAGE ON SCHEMA public TO lu_auth_runtime;
        GRANT SELECT, INSERT, UPDATE ON TABLE public.lu_country, public.lu_city TO lu_auth_runtime;
        GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.lu_country_id_seq, public.lu_city_id_seq
            TO lu_auth_runtime;
    END IF;
END
$grant$;

COMMIT;
