BEGIN;

-- MIG-F3-PG-LABORATORIES-002
-- Laboratory is tenant-local; faculty_id is an opaque control-plane id and
-- city_id is a local catalogue id. Cross-database joins stay in application code.
SELECT pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext('lu:tenant:academic:laboratories:0003')
);

CREATE TABLE IF NOT EXISTS public.lu_laboratory (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    faculty_id bigint NOT NULL,
    code varchar(20) NOT NULL,
    name varchar(200) NOT NULL,
    type varchar(100),
    building varchar(100),
    block varchar(50),
    floor varchar(50),
    room varchar(100),
    description varchar(1000),
    city_id bigint,
    status integer NOT NULL DEFAULT 0,
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz,
    CONSTRAINT ck_lu_laboratory_status CHECK (status IN (0, 1, 2))
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_lu_laboratory_site_code_active
    ON public.lu_laboratory (site_id, lower(code)) WHERE status <> 2;
CREATE UNIQUE INDEX IF NOT EXISTS ux_lu_laboratory_site_faculty_name_active
    ON public.lu_laboratory (site_id, faculty_id, lower(name)) WHERE status <> 2;
CREATE INDEX IF NOT EXISTS ix_lu_laboratory_site_faculty
    ON public.lu_laboratory (site_id, faculty_id, lower(name));

DO $grant$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'lu_auth_runtime') THEN
        GRANT SELECT, INSERT, UPDATE ON TABLE public.lu_laboratory TO lu_auth_runtime;
        GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.lu_laboratory_id_seq TO lu_auth_runtime;
    END IF;
END
$grant$;

COMMIT;
