BEGIN;

-- MIG-F5-PG-EQUIPMENT-001
-- Equipment definitions are tenant-local. Physical units/Kardex remain a later slice.
SELECT pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext('lu:tenant:equipment:0004')
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_lu_equipment_site_catalog_code_active
    ON public.lu_equipment (site_id, lower(catalog_code))
    WHERE catalog_code IS NOT NULL AND status <> 2;

CREATE UNIQUE INDEX IF NOT EXISTS ux_lu_equipment_site_name_model_active
    ON public.lu_equipment (site_id, lower(name), lower(COALESCE(model, '')))
    WHERE status <> 2;

CREATE TABLE IF NOT EXISTS public.lu_equipment_note (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    equipment_id bigint NOT NULL,
    note varchar(500) NOT NULL,
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lu_equipment_note_equipment
        FOREIGN KEY (equipment_id) REFERENCES public.lu_equipment (id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS ix_lu_equipment_note_site_equipment
    ON public.lu_equipment_note (site_id, equipment_id, created_at);

DO $grant$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'lu_auth_runtime') THEN
        GRANT SELECT, INSERT, UPDATE ON TABLE public.lu_equipment TO lu_auth_runtime;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.lu_equipment_note TO lu_auth_runtime;
        GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.lu_equipment_note_id_seq TO lu_auth_runtime;
    END IF;
END
$grant$;

COMMIT;
