BEGIN;

-- MIG-F6-PG-EQUIPMENT-UNITS-001
-- Physical units remain tenant-local. Their operational site is derived from
-- the laboratory; site_id is retained only as a defensive routing key for
-- legacy rows and is never accepted from the browser.
SELECT pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext('lu:tenant:equipment-units:0005')
);

DO $constraints$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_catalog.pg_constraint
        WHERE conname = 'ck_lu_equipment_unit_status'
          AND conrelid = 'public.lu_equipment_unit'::regclass
    ) THEN
        ALTER TABLE public.lu_equipment_unit
            ADD CONSTRAINT ck_lu_equipment_unit_status
            CHECK (current_status IN (0, 1, 2, 3, 4, 5, 6, 10, 99));
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_catalog.pg_constraint
        WHERE conname = 'ck_lu_equipment_unit_location_resolution'
          AND conrelid = 'public.lu_equipment_unit'::regclass
    ) THEN
        ALTER TABLE public.lu_equipment_unit
            ADD CONSTRAINT ck_lu_equipment_unit_location_resolution
            CHECK (location_resolution_status IN (0, 1));
    END IF;
END
$constraints$;

CREATE TABLE IF NOT EXISTS public.lu_equipment_unit_state_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    equipment_unit_id bigint NOT NULL,
    status integer NOT NULL,
    start_date timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_date timestamptz,
    reason varchar(500),
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz,
    CONSTRAINT ck_lu_equipment_unit_history_status
        CHECK (status IN (0, 1, 2, 3, 4, 5, 6, 10, 99)),
    CONSTRAINT ck_lu_equipment_unit_history_dates
        CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE INDEX IF NOT EXISTS ix_lu_equipment_unit_history_site_unit_start
    ON public.lu_equipment_unit_state_history (site_id, equipment_unit_id, start_date DESC, id DESC);

CREATE INDEX IF NOT EXISTS ix_lu_equipment_unit_site_equipment
    ON public.lu_equipment_unit (site_id, equipment_id, current_status);

DO $grant$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'lu_auth_runtime') THEN
        GRANT SELECT, INSERT, UPDATE ON TABLE public.lu_equipment_unit TO lu_auth_runtime;
        GRANT SELECT, INSERT, UPDATE ON TABLE public.lu_equipment_unit_state_history TO lu_auth_runtime;
        GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.lu_equipment_unit_id_seq TO lu_auth_runtime;
        GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.lu_equipment_unit_state_history_id_seq TO lu_auth_runtime;
    END IF;
END
$grant$;

COMMIT;
