BEGIN;

-- MIG-F9-PG-VERIFICATIONS-001
-- L-6 verification data is tenant-local. ManagementId and EquipmentUnitId
-- are always checked in the same tenant before a write is accepted.
SELECT pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext('lu:tenant:verifications:0007')
);

CREATE TABLE IF NOT EXISTS public.lu_verification_check_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(300) NOT NULL,
    category varchar(100),
    display_order integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.lu_verification (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    equipment_unit_id bigint NOT NULL,
    management_id bigint NOT NULL,
    verification_date date NOT NULL DEFAULT CURRENT_DATE,
    observations varchar(2000),
    physical_condition integer NOT NULL,
    observed_equipment_status integer,
    status integer NOT NULL DEFAULT 0,
    responsible_person_id bigint,
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz,
    CONSTRAINT ck_lu_verification_condition CHECK (physical_condition BETWEEN 1 AND 5),
    CONSTRAINT ck_lu_verification_status CHECK (status IN (0, 1, 2, 3, 99)),
    CONSTRAINT ck_lu_verification_equipment_status CHECK (observed_equipment_status IS NULL OR observed_equipment_status IN (0, 1, 2, 3, 4, 5, 6, 10, 99))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_lu_verification_site_management_unit
    ON public.lu_verification (site_id, management_id, equipment_unit_id)
    WHERE status <> 99;
CREATE INDEX IF NOT EXISTS ix_lu_verification_site_lab_date
    ON public.lu_verification (site_id, verification_date DESC, status);

CREATE TABLE IF NOT EXISTS public.lu_verification_check_result (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    verification_id bigint NOT NULL,
    check_item_id bigint NOT NULL,
    result integer NOT NULL DEFAULT 0,
    CONSTRAINT ck_lu_verification_result CHECK (result IN (0, 1)),
    CONSTRAINT ux_lu_verification_result_item UNIQUE (verification_id, check_item_id)
);

CREATE TABLE IF NOT EXISTS public.lu_verification_fault (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    verification_id bigint NOT NULL,
    description varchar(255) NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz
);
CREATE INDEX IF NOT EXISTS ix_lu_verification_fault_site_verification
    ON public.lu_verification_fault (site_id, verification_id, is_deleted);

DO $grant$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'lu_auth_runtime') THEN
        GRANT SELECT, INSERT, UPDATE ON TABLE public.lu_verification_check_item, public.lu_verification, public.lu_verification_check_result, public.lu_verification_fault TO lu_auth_runtime;
        GRANT DELETE ON TABLE public.lu_verification_check_result TO lu_auth_runtime;
        GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.lu_verification_check_item_id_seq, public.lu_verification_id_seq, public.lu_verification_check_result_id_seq, public.lu_verification_fault_id_seq TO lu_auth_runtime;
    END IF;
END
$grant$;

COMMIT;
