BEGIN;

-- MIG-F10-PG-REQUESTS-001
-- L-7 requests and their normalized affected-unit links remain tenant-local.
-- The management plan is advanced in the same tenant transaction; no
-- cross-database foreign key or browser-provided site is accepted.
SELECT pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext('lu:tenant:requests:0008')
);

CREATE TABLE IF NOT EXISTS public.lu_request (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    laboratory_id bigint,
    location_resolution_status integer NOT NULL DEFAULT 1,
    import_batch_id bigint,
    equipment_id bigint,
    equipment_unit_id bigint,
    management_id bigint NOT NULL,
    requested_by_id uuid,
    requested_by_person_id bigint,
    description varchar(1000) NOT NULL,
    priority integer NOT NULL DEFAULT 1,
    observations varchar(500),
    suggestion varchar(2000),
    request_date date,
    estimated_repair_time varchar(100),
    status integer NOT NULL DEFAULT 0,
    approved_by_id uuid,
    approval_date timestamptz,
    rejection_reason varchar(500),
    type integer NOT NULL DEFAULT 1,
    investment_code varchar(50),
    cost_center varchar(100),
    historical_source_key varchar(200),
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz,
    row_version bigint NOT NULL DEFAULT 0,
    CONSTRAINT ck_lu_request_location CHECK (location_resolution_status IN (0, 1)),
    CONSTRAINT ck_lu_request_priority CHECK (priority BETWEEN 0 AND 3),
    CONSTRAINT ck_lu_request_status CHECK (status IN (0, 1, 2, 3, 4, 5, 99)),
    CONSTRAINT ck_lu_request_type CHECK (type IN (1, 2, 3)),
    CONSTRAINT ck_lu_request_description CHECK (length(btrim(description)) > 0)
);

CREATE INDEX IF NOT EXISTS ix_lu_request_site_management_status
    ON public.lu_request (site_id, management_id, status, request_date DESC);
CREATE INDEX IF NOT EXISTS ix_lu_request_site_unit
    ON public.lu_request (site_id, equipment_unit_id, status);
CREATE INDEX IF NOT EXISTS ix_lu_request_site_priority
    ON public.lu_request (site_id, priority, request_date DESC);
CREATE UNIQUE INDEX IF NOT EXISTS ux_lu_request_active_technical_management_unit
    ON public.lu_request (site_id, management_id, equipment_unit_id)
    WHERE equipment_unit_id IS NOT NULL AND type = 1 AND status <> 99;

CREATE TABLE IF NOT EXISTS public.lu_request_equipment_unit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    request_id bigint NOT NULL,
    equipment_unit_id bigint NOT NULL,
    is_legacy_primary boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    deactivated_at timestamptz,
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz,
    CONSTRAINT ux_lu_request_unit UNIQUE (site_id, request_id, equipment_unit_id)
);
CREATE INDEX IF NOT EXISTS ix_lu_request_unit_site_request
    ON public.lu_request_equipment_unit (site_id, request_id, is_active);

DO $grant$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'lu_auth_runtime') THEN
        GRANT SELECT, INSERT, UPDATE ON TABLE public.lu_request, public.lu_request_equipment_unit TO lu_auth_runtime;
        GRANT DELETE ON TABLE public.lu_request_equipment_unit TO lu_auth_runtime;
        GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.lu_request_id_seq, public.lu_request_equipment_unit_id_seq TO lu_auth_runtime;
    END IF;
END
$grant$;

COMMIT;
