BEGIN;

-- MIG-F11-PG-MAINTENANCES-001
-- L-8 maintenance execution is tenant-local. Tasks, participants, requests
-- and costs are normalized child records; history is retained by soft flags.
SELECT pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext('lu:tenant:maintenances:0009')
);

CREATE TABLE IF NOT EXISTS public.lu_maintenance (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    equipment_unit_id bigint NOT NULL,
    maintenance_type integer NOT NULL DEFAULT 99,
    management_id bigint NOT NULL,
    service_type integer NOT NULL DEFAULT 0,
    institutional_code varchar(50),
    technician_id bigint,
    request_id bigint,
    scheduled_date date,
    start_date timestamptz,
    end_date timestamptz,
    description varchar(2000),
    status integer NOT NULL DEFAULT 0,
    completion_percentage integer NOT NULL DEFAULT 0,
    step1_cleaning boolean NOT NULL DEFAULT false,
    step2_calibration boolean NOT NULL DEFAULT false,
    step3_testing boolean NOT NULL DEFAULT false,
    step4_final_review boolean NOT NULL DEFAULT false,
    estimated_cost numeric(18,2),
    actual_cost numeric(18,2),
    recommendations varchar(1000),
    suggested_next_maintenance_date date,
    satisfaction_level integer,
    observations varchar(1000),
    historical_source_key varchar(200),
    import_batch_id bigint,
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz,
    row_version bigint NOT NULL DEFAULT 0,
    CONSTRAINT ck_lu_maintenance_type CHECK (maintenance_type IN (1, 2, 3, 4, 5, 99)),
    CONSTRAINT ck_lu_maintenance_service CHECK (service_type IN (0, 1)),
    CONSTRAINT ck_lu_maintenance_status CHECK (status IN (0, 1, 2, 3, 99)),
    CONSTRAINT ck_lu_maintenance_progress CHECK (completion_percentage BETWEEN 0 AND 100),
    CONSTRAINT ck_lu_maintenance_cost CHECK ((estimated_cost IS NULL OR estimated_cost >= 0) AND (actual_cost IS NULL OR actual_cost >= 0)),
    CONSTRAINT ck_lu_maintenance_satisfaction CHECK (satisfaction_level IS NULL OR satisfaction_level BETWEEN 1 AND 5)
);
CREATE INDEX IF NOT EXISTS ix_lu_maintenance_site_management_status
    ON public.lu_maintenance (site_id, management_id, status, scheduled_date);
CREATE INDEX IF NOT EXISTS ix_lu_maintenance_site_unit
    ON public.lu_maintenance (site_id, equipment_unit_id, status);
CREATE UNIQUE INDEX IF NOT EXISTS ux_lu_maintenance_active_plan_unit
    ON public.lu_maintenance (site_id, management_id, equipment_unit_id)
    WHERE status <> 99;

CREATE TABLE IF NOT EXISTS public.lu_maintenance_task (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    maintenance_id bigint NOT NULL,
    description varchar(255) NOT NULL,
    is_completed boolean NOT NULL DEFAULT false,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz,
    CONSTRAINT ck_lu_maintenance_task_description CHECK (length(btrim(description)) > 0)
);
CREATE INDEX IF NOT EXISTS ix_lu_maintenance_task_site_parent
    ON public.lu_maintenance_task (site_id, maintenance_id, is_deleted);

CREATE TABLE IF NOT EXISTS public.lu_maintenance_participant (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    maintenance_id bigint NOT NULL,
    person_id bigint NOT NULL,
    role integer NOT NULL DEFAULT 1,
    is_primary boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    assigned_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    unassigned_at timestamptz,
    CONSTRAINT ck_lu_maintenance_participant_role CHECK (role BETWEEN 1 AND 4)
);
CREATE INDEX IF NOT EXISTS ix_lu_maintenance_participant_site_parent
    ON public.lu_maintenance_participant (site_id, maintenance_id, is_active);

CREATE TABLE IF NOT EXISTS public.lu_maintenance_request (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    maintenance_id bigint NOT NULL,
    request_id bigint NOT NULL,
    is_legacy_primary boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    deactivated_at timestamptz,
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz,
    CONSTRAINT ux_lu_maintenance_request UNIQUE (site_id, maintenance_id, request_id)
);

CREATE TABLE IF NOT EXISTS public.lu_maintenance_cost (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    maintenance_id bigint NOT NULL,
    concept varchar(200) NOT NULL,
    description varchar(500),
    quantity numeric(18,4) NOT NULL DEFAULT 1,
    unit_of_measure varchar(50),
    unit_price numeric(18,2) NOT NULL DEFAULT 0,
    category integer NOT NULL DEFAULT 1,
    provider varchar(200),
    cost_date date,
    invoice_number varchar(100),
    is_deleted boolean NOT NULL DEFAULT false,
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz,
    CONSTRAINT ck_lu_maintenance_cost_values CHECK (quantity > 0 AND unit_price >= 0),
    CONSTRAINT ck_lu_maintenance_cost_concept CHECK (length(btrim(concept)) > 0)
);
CREATE INDEX IF NOT EXISTS ix_lu_maintenance_cost_site_parent
    ON public.lu_maintenance_cost (site_id, maintenance_id, is_deleted);

DO $grant$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'lu_auth_runtime') THEN
        GRANT SELECT, INSERT, UPDATE ON TABLE public.lu_maintenance, public.lu_maintenance_task, public.lu_maintenance_participant, public.lu_maintenance_request, public.lu_maintenance_cost TO lu_auth_runtime;
        GRANT DELETE ON TABLE public.lu_maintenance_task, public.lu_maintenance_request TO lu_auth_runtime;
        GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.lu_maintenance_id_seq, public.lu_maintenance_task_id_seq, public.lu_maintenance_participant_id_seq, public.lu_maintenance_request_id_seq, public.lu_maintenance_cost_id_seq TO lu_auth_runtime;
    END IF;
END
$grant$;

COMMIT;
