BEGIN;

-- MIG-F12-PG-DEPARTURES-001
-- L-3 exits/returns remain tenant-local. A final exit moves the plan to
-- Kardex, while drafts keep the plan in Exit/AwaitingDeparture.
SELECT pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext('lu:tenant:departures:0010')
);

CREATE TABLE IF NOT EXISTS public.lu_departure (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    management_id bigint NOT NULL,
    equipment_unit_id bigint,
    borrower_id bigint,
    origin_laboratory_id bigint,
    destination varchar(200),
    historical_source_key varchar(200),
    import_batch_id bigint,
    type integer NOT NULL DEFAULT 2,
    departure_date date NOT NULL DEFAULT CURRENT_DATE,
    estimated_return_date date,
    actual_return_date timestamptz,
    departure_observations varchar(500),
    return_observations varchar(500),
    status integer NOT NULL DEFAULT 0,
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz,
    row_version bigint NOT NULL DEFAULT 0,
    CONSTRAINT ck_lu_departure_type CHECK (type IN (1, 2, 3, 4, 5)),
    CONSTRAINT ck_lu_departure_status CHECK (status IN (0, 1, 2, 99))
);
CREATE INDEX IF NOT EXISTS ix_lu_departure_site_management_status
    ON public.lu_departure (site_id, management_id, status, departure_date DESC);
CREATE INDEX IF NOT EXISTS ix_lu_departure_site_unit
    ON public.lu_departure (site_id, equipment_unit_id, status);

CREATE TABLE IF NOT EXISTS public.lu_departure_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    departure_id bigint NOT NULL,
    equipment_unit_id bigint,
    article_id bigint,
    product_name varchar(200),
    quantity integer,
    unit_of_measure varchar(50) DEFAULT 'UNIDAD',
    returned_quantity integer,
    observations varchar(500),
    is_removed boolean NOT NULL DEFAULT false,
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz,
    CONSTRAINT ck_lu_departure_item_quantity CHECK (quantity IS NULL OR quantity > 0),
    CONSTRAINT ck_lu_departure_item_returned CHECK (returned_quantity IS NULL OR returned_quantity >= 0)
);
CREATE INDEX IF NOT EXISTS ix_lu_departure_item_site_parent
    ON public.lu_departure_item (site_id, departure_id, is_removed);

DO $grant$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'lu_auth_runtime') THEN
        GRANT SELECT, INSERT, UPDATE ON TABLE public.lu_departure, public.lu_departure_item TO lu_auth_runtime;
        GRANT DELETE ON TABLE public.lu_departure_item TO lu_auth_runtime;
        GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.lu_departure_id_seq, public.lu_departure_item_id_seq TO lu_auth_runtime;
    END IF;
END
$grant$;

COMMIT;
