BEGIN;

-- MIG-F14-PG-ACQUISITIONS-001
-- L-12 reuses the tenant request row with type=2 and stores cost history in
-- a dedicated child table. The management plan remains the wizard authority.
SELECT pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext('lu:tenant:acquisitions:0011')
);

CREATE TABLE IF NOT EXISTS public.lu_request_cost (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    request_id bigint NOT NULL,
    concept varchar(200) NOT NULL,
    description varchar(500),
    quantity numeric(18,4) NOT NULL DEFAULT 1,
    unit_of_measure varchar(50),
    unit_price numeric(18,2) NOT NULL DEFAULT 0,
    category integer NOT NULL DEFAULT 1,
    provider varchar(200),
    cost_date date,
    invoice_number varchar(100),
    is_deleted boolean NOT NULL DEFAULT false,
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz,
    CONSTRAINT ck_lu_request_cost_values CHECK (quantity > 0 AND unit_price >= 0),
    CONSTRAINT ck_lu_request_cost_concept CHECK (length(btrim(concept)) > 0)
);
CREATE INDEX IF NOT EXISTS ix_lu_request_cost_site_parent
    ON public.lu_request_cost (site_id, request_id, is_deleted);

DO $grant$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'lu_auth_runtime') THEN
        GRANT SELECT, INSERT, UPDATE ON TABLE public.lu_request_cost TO lu_auth_runtime;
        GRANT DELETE ON TABLE public.lu_request_cost TO lu_auth_runtime;
        GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.lu_request_cost_id_seq TO lu_auth_runtime;
    END IF;
END
$grant$;

COMMIT;
