BEGIN;

-- MIG-F4-PG-PEOPLE-001
-- Operational persons/technicians stay in the tenant database. They are not
-- identity accounts: control-plane users remain in lu_user and memberships.
SELECT pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext('lu:tenant:people:0012')
);

CREATE TABLE IF NOT EXISTS public.lu_person (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id uuid NOT NULL,
    actor_code varchar(30),
    person_type varchar(20) NOT NULL DEFAULT 'internal',
    name varchar(200) NOT NULL,
    email varchar(100),
    phone_number varchar(20),
    is_entity boolean NOT NULL DEFAULT false,
    address varchar(500),
    category integer NOT NULL DEFAULT 99,
    status integer NOT NULL DEFAULT 0,
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz,
    CONSTRAINT ck_lu_person_type CHECK (person_type IN ('internal', 'external')),
    CONSTRAINT ck_lu_person_category CHECK (category IN (1, 2, 3, 4, 5, 99)),
    CONSTRAINT ck_lu_person_status CHECK (status IN (0, 1, 2)),
    CONSTRAINT ck_lu_person_name CHECK (length(btrim(name)) > 0),
    CONSTRAINT ck_lu_person_external_address CHECK (person_type <> 'external' OR length(btrim(coalesce(address, ''))) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_lu_person_site_actor_code
    ON public.lu_person (site_id, lower(actor_code))
    WHERE actor_code IS NOT NULL AND status <> 2;
CREATE INDEX IF NOT EXISTS ix_lu_person_site_status_type
    ON public.lu_person (site_id, status, person_type, lower(name));
CREATE INDEX IF NOT EXISTS ix_lu_person_site_email
    ON public.lu_person (site_id, lower(email));

DO $grant$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'lu_auth_runtime') THEN
        GRANT SELECT, INSERT, UPDATE ON TABLE public.lu_person TO lu_auth_runtime;
        GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.lu_person_id_seq TO lu_auth_runtime;
    END IF;
END
$grant$;

COMMIT;
