BEGIN;

-- MIG-F3-PG-ACADEMIC-001
-- Additive control-plane catalogue migration. It intentionally does not alter
-- the immutable 0001-0003 files; promotion must register this file in the
-- deployment migration manifest for each control-plane environment.
SELECT pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext('lu:identity-control-plane:0004-academic')
);

CREATE TABLE IF NOT EXISTS public.lu_faculty (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    code varchar(50),
    description varchar(500),
    status integer NOT NULL DEFAULT 0,
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz,
    CONSTRAINT ck_lu_faculty_status CHECK (status IN (0, 1, 2))
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_lu_faculty_name_active
    ON public.lu_faculty (lower(name)) WHERE status <> 2;
CREATE UNIQUE INDEX IF NOT EXISTS ux_lu_faculty_code_active
    ON public.lu_faculty (lower(code)) WHERE code IS NOT NULL AND status <> 2;

CREATE TABLE IF NOT EXISTS public.lu_career (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(30),
    name varchar(200) NOT NULL,
    faculty_id bigint,
    status integer NOT NULL DEFAULT 0,
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz,
    CONSTRAINT ck_lu_career_status CHECK (status IN (0, 1, 2)),
    CONSTRAINT fk_lu_career_faculty FOREIGN KEY (faculty_id)
        REFERENCES public.lu_faculty (id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_lu_career_name_active
    ON public.lu_career (lower(name)) WHERE status <> 2;
CREATE UNIQUE INDEX IF NOT EXISTS ux_lu_career_code_active
    ON public.lu_career (lower(code)) WHERE code IS NOT NULL AND status <> 2;

CREATE TABLE IF NOT EXISTS public.lu_site_career (
    site_id uuid NOT NULL REFERENCES public.lu_site (id) ON DELETE RESTRICT,
    career_id bigint NOT NULL REFERENCES public.lu_career (id) ON DELETE RESTRICT,
    status integer NOT NULL DEFAULT 0,
    created_by_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_id uuid,
    updated_at timestamptz,
    PRIMARY KEY (site_id, career_id),
    CONSTRAINT ck_lu_site_career_status CHECK (status IN (0, 1, 2))
);

DO $grant$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'lu_auth_runtime') THEN
        GRANT SELECT, INSERT, UPDATE ON TABLE public.lu_faculty, public.lu_career, public.lu_site_career TO lu_auth_runtime;
        GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.lu_faculty_id_seq, public.lu_career_id_seq TO lu_auth_runtime;
    END IF;
END
$grant$;

COMMIT;
