/**
 * Frozen deterministic test corpus for the ASP.NET Identity V2/V3 parser
 * and runtime verifiers.
 *
 * Generated once with `node:crypto` from fixed salts and synthetic
 * (non-real) passwords; the resulting Base64 strings are stored as
 * literals below. The corpus covers:
 *  - V2 (PBKDF2-HMAC-SHA1, 1000 iterations) — marker 0x00.
 *  - V3 with PRF 0 (SHA1), 1 (SHA256) and 2 (SHA512).
 *  - Boundary sizes: iterations 1000, salt 16 and 64, subkey 16 and 64.
 *  - A malformed corpus for the parser reject cases (non-canonical base64,
 *    whitespace, URL-safe chars, bad marker 0x02, truncated, trailing
 *    extra byte, iterations 999 and 1_000_001, salt 15 and 65, subkey 15
 *    and 65, decoded > 141 bytes, PRF 3, V2 with 50 bytes).
 *
 * A re-derivation test in `identity.password.e2e-spec.ts` proves the
 * literals were generated by the canonical PBKDF2 + standard-base64
 * algorithm (so a regression in this fixture file is detected by the
 * test even though the parser test uses the literals directly).
 */

export interface IdentityVectorFixture {
  readonly name: string;
  readonly version: 2 | 3;
  readonly prf: 'sha1' | 'sha256' | 'sha512';
  readonly iterations: number;
  readonly saltLength: number;
  readonly subkeyLength: number;
  readonly password: string;
  readonly base64: string;
}

export const IDENTITY_VECTORS: readonly IdentityVectorFixture[] = Object.freeze([
  Object.freeze({
    name: 'V2-sha1-1000-salt16-sub32',
    version: 2,
    prf: 'sha1',
    iterations: 1000,
    saltLength: 16,
    subkeyLength: 32,
    password: 'S3cret-Migration-Fixture-V2',
    base64: 'AAARIjNEVWZ3iJmqu8zd7v9C52Q8RiR8afRVhBAGeYVprUXxHXvDmhYnmN6Q1euRCg==',
  }),
  Object.freeze({
    name: 'V3-sha1-1000-salt16-sub32',
    version: 3,
    prf: 'sha1',
    iterations: 1000,
    saltLength: 16,
    subkeyLength: 32,
    password: 'S3cret-Migration-Fixture-V3-sha1',
    base64: 'AQAAAAAAAAPoAAAAEBEiM0RVZneImaq7zN3u/wClvO+RtdOn0o86o/8vYvR7bYc9u4vueh7dN3fe+UYnSA==',
  }),
  Object.freeze({
    name: 'V3-sha256-100000-salt16-sub32',
    version: 3,
    prf: 'sha256',
    iterations: 100_000,
    saltLength: 16,
    subkeyLength: 32,
    password: 'S3cret-Migration-Fixture-V3-sha256',
    base64: 'AQAAAAEAAYagAAAAECIzRFVmd4iZqrvM3e7/ABHLX/qOzj8U5T4WPW+HeZk45MOUC8vXrvQbLdsRNBPszA==',
  }),
  Object.freeze({
    name: 'V3-sha512-100000-salt16-sub32',
    version: 3,
    prf: 'sha512',
    iterations: 100_000,
    saltLength: 16,
    subkeyLength: 32,
    password: 'S3cret-Migration-Fixture-V3-sha512',
    base64: 'AQAAAAIAAYagAAAAEDNEVWZ3iJkAqrvM3e7/ABHS54ix/0ch4UCW8Gkz5hpdx/TTgwVW2bsi3uujf/bwrA==',
  }),
  Object.freeze({
    name: 'V3-sha256-1000-salt16-sub16',
    version: 3,
    prf: 'sha256',
    iterations: 1000,
    saltLength: 16,
    subkeyLength: 16,
    password: 'S3cret-Fixture-Boundary-salt16-sub16',
    base64: 'AQAAAAEAAAPoAAAAEN6tvu/K/rq+ESIzRFVmd4iW+1ijj8k49Yhek1Rcg+rI',
  }),
  Object.freeze({
    name: 'V3-sha512-100000-salt64-sub64',
    version: 3,
    prf: 'sha512',
    iterations: 100_000,
    saltLength: 64,
    subkeyLength: 64,
    password: 'S3cret-Fixture-Boundary-salt64-sub64',
    base64:
      'AQAAAAIAAYagAAAAQAEjRWeJq83vASNFZ4mrze8BI0VniavN7wEjRWeJq83vASNFZ4mrze8BI0VniavN7wEjRWeJq83vASNFZ4mrze9oxL8p9OIwzjclJOaxWUtSZko5D7M5xFM0NApFfDFCGePDGmyNC7UExSMG6sExkj+vqCZ9Bh8OUcmNk2WQdGPh',
  }),
]);

/**
 * Malformed inputs that the parser MUST reject. Every entry is a valid
 * standard-base64 string on its own (length multiple of 4) so the test
 * can assert the SPECIFIC shape violation, not just a generic base64
 * failure. Whitespace and URL-safe inputs are pre-validated here too.
 */
export const MALFORMED_IDENTITY_VECTORS: ReadonlyArray<{
  readonly name: string;
  readonly base64: string;
}> = Object.freeze([
  { name: 'noncanonical-trailing-bits-AB==', base64: 'AB==' },
  {
    name: 'whitespace-leading',
    base64: ' AAARIjNEVWZ3iJmqu8zd7v9C52Q8RiR8afRVhBAGeYVprUXxHXvDmhYnmN6Q1euRCg==',
  },
  {
    name: 'whitespace-internal',
    base64: 'AAARIj NEVWZ3iJmqu8zd7v9C52Q8RiR8afRVhBAGeYVprUXxHXvDmhYnmN6Q1euRCg==',
  },
  {
    name: 'whitespace-trailing',
    base64: 'AAARIjNEVWZ3iJmqu8zd7v9C52Q8RiR8afRVhBAGeYVprUXxHXvDmhYnmN6Q1euRCg== ',
  },
  {
    name: 'url-safe-dash-replaces-plus',
    base64: 'AQAAAAEAAYagAAAAECIzRFVmd4iZqrvM3e7/ABHLX/qOzj8U5T4WPW-HeZk45MOUC8vXrvQbLdsRNBPszA==',
  },
  {
    name: 'url-safe-underscore-replaces-slash',
    base64: 'AQAAAAEAAYagAAAAECIzRFVmd4iZqrvM3e7_ABHLX_qOzj8U5T4WPW+HeZk45MOUC8vXrvQbLdsRNBPszA==',
  },
  { name: 'missing-padding-AAE', base64: 'AAE' },
  { name: 'excess-padding-AAE====', base64: 'AAE====' },
  { name: 'mid-string-padding-AAE=A', base64: 'AAE=A' },
  {
    name: 'unknown-marker-0x02',
    base64: 'AgARIjNEVWZ3iJmqu8zd7v9C52Q8RiR8afRVhBAGeYVprUXxHXvDmhYnmN6Q1euRCg==',
  },
  {
    name: 'v2-with-50-bytes',
    base64: 'AAARIjNEVWZ3iJmqu8zd7v9C52Q8RiR8afRVhBAGeYVprUXxHXvDmhYnmN6Q1euRCgA=',
  },
  { name: 'v3-truncated-header-AQAAA', base64: 'AQAAA' },
  {
    name: 'v3-prf-3-unsupported',
    base64: 'AQAAAAMAAAPoAAAAEC+ZCiTkampRRiDx2AMV0q/W0aylwh4DnsrLzXEguYEi',
  },
  {
    name: 'v3-iterations-999',
    base64: 'AQAAAAAAAAPnAAAAEHvEtbFAVZylVNeGF/Ib6IxG9YbMLAxzoj8+gemH8ClQ',
  },
  {
    name: 'v3-iterations-1000001',
    base64: 'AQAAAAAAD0JBAAAAENyB8ck7puK/b6nY5qzyU3qEP0npwydI0Gy2+kyyB07a',
  },
  { name: 'v3-salt-15', base64: 'AQAAAAAAAAPoAAAAD3A6OO92kIKs0wa9h6LHF0u1r0D7l2keV5ZxUgoW3nc=' },
  {
    name: 'v3-salt-65',
    base64:
      'AQAAAAAAAAPoAAAAQXz+H/GYxpopZRmdoRz12YlpZ8A4Wc2F0xJM/LvfCrgmko5R6fdUpVSg316RBcWOAZeeRRkXzyV1Iym9jw+t9YDtB32u1IyQY1C6w61UpS+tiQ==',
  },
  { name: 'v3-subkey-15', base64: 'AQAAAAAAAAPoAAAAEN+214EGCiFYb+rN01moi3ePVQKTCkKbXhCzLmrt8nY=' },
  {
    name: 'v3-subkey-65',
    base64:
      'AQAAAAAAAAPoAAAAEIAIMLirWi35hZSpRUGfGVlwdQ6dGvzCSvAijEgxyTevvx2681p3GWRzVnIKlhFNSj5He5ZSba50xKP8YU+08g33CoKcyyFSe9Ne09iKe+BipQ==',
  },
  {
    name: 'decoded-exceeds-141-bytes',
    base64:
      'dAuI5+Msztk5DzTsS0X7exgq9tnVEvKXyUVj/l2GuFGXIrFWiYchLBIjqz0fG0jKsKZYAVaSn8ThYyfWdE7Ga2hRI7i8R4e8l/vHnDKnNAMKiIeVHI9ZZcW2W308jalLpyXEO6KwJG6RGNq1R+8+P36M6KH+7FbU6CBZKRY6ksQAdJtrIGJ1DWPAamO6/g==',
  },
]);

/** A standalone UTF-8 multibyte emoji + symbol fixture for the password policy tests. */
export const MULTIBYTE_PASSWORD_FIXTURES: ReadonlyArray<{
  readonly label: string;
  readonly value: string;
  readonly codePoints: number;
  readonly utf8Bytes: number;
}> = Object.freeze([
  Object.freeze({ label: 'emoji-smiley', value: 'Aa1!😀', codePoints: 5, utf8Bytes: 8 }),
  Object.freeze({ label: 'emoji-astronaut', value: 'Aa1!🚀B', codePoints: 6, utf8Bytes: 9 }),
  Object.freeze({ label: 'cyrillic-mixed', value: 'Aa1!ЖZ', codePoints: 6, utf8Bytes: 7 }),
  Object.freeze({ label: 'latin-extended', value: 'Aa1!Ñ', codePoints: 5, utf8Bytes: 6 }),
]);
