/**
 * Schema manifest and verification for the identity control-plane migration (0001).
 *
 * `verifySchema` compares the live PostgreSQL catalog (information_schema + pg_catalog)
 * against a declarative manifest. It reads no business rows and prints no secrets.
 *
 * The expected manifest for 0001 is exhaustive: every column, constraint and index on the
 * four target tables is declared. Any missing or extra object in those tables is a failure.
 */
import type { Client } from 'pg';
import { type ControlPlaneTable, type TargetTable } from './migration-plan.js';

export interface ColumnSpec {
  readonly name: string;
  readonly dataType: string;
  readonly udtName: string;
  readonly charMaxLength: number | null;
  readonly isNullable: boolean;
  readonly columnDefault: string | null;
  /**
   * Identity mode declared by `GENERATED <mode> AS IDENTITY`. When set, the
   * verifier expects `information_schema.columns.column_default = NULL`
   * (PG does not surface IDENTITY defaults in `column_default`), asserts
   * `pg_attribute.attidentity = 'd'` (BY DEFAULT) on the owning column and
   * accepts the supplemental ownership `pg_depend.deptype = 'i'`
   * (internal/identity link from sequence -> column) in addition to the
   * legacy `'a'` (auto/serial) link. Only `'BY DEFAULT'` is permitted by
   * the contract; `ALWAYS` would require a separate expectation.
   */
  readonly identity?: IdentitySpec;
}

export interface IdentitySpec {
  readonly generated: 'BY DEFAULT';
  readonly sequence: string;
}

export interface PrimaryKeySpec {
  readonly columns: readonly string[];
}

export interface UniqueSpec {
  readonly columns: readonly string[];
}

export interface ForeignKeySpec {
  readonly columns: readonly string[];
  readonly referencesTable: string;
  readonly referencesColumns: readonly string[];
  readonly deleteAction: 'RESTRICT';
}

export interface CheckSpec {
  /** Normalized CHECK expression (without the CHECK keyword and without autogenerated name). */
  readonly definition: string;
}

export interface IndexSpec {
  readonly name: string;
  readonly table: string;
  readonly columns: readonly string[];
  readonly unique: boolean;
  /** Normalized partial-index predicate, or null for a full index. */
  readonly where: string | null;
}

export interface TableManifest {
  readonly columns: readonly ColumnSpec[];
  readonly primaryKey: PrimaryKeySpec;
  readonly uniques: readonly UniqueSpec[];
  readonly foreignKeys: readonly ForeignKeySpec[];
  readonly checks: readonly CheckSpec[];
  readonly indexes: readonly IndexSpec[];
}

export interface SchemaManifest<TTable extends string = TargetTable> {
  readonly schema: string;
  readonly tables: Readonly<Record<TTable, TableManifest>>;
}

export interface SchemaVerification {
  readonly passed: boolean;
  readonly diffs: readonly string[];
  readonly actualTableNames: readonly string[];
}

// ---------------------------------------------------------------------------
// Normalizers
// ---------------------------------------------------------------------------

function collapseWhitespace(value: string): string {
  return value.trim().replace(/\s+/g, ' ');
}

function lowercase(value: string): string {
  return value.toLowerCase();
}

function stripPublicSchema(value: string): string {
  return value.replace(/\bpublic\./g, '');
}

function stripTypeCasts(value: string): string {
  return value.replace(
    /::\s*(?:text|bpchar|boolean|bigint|uuid|numeric|integer|int4|int8|smallint|decimal|real|double precision|date|time)\b/g,
    '',
  );
}

/**
 * Strip PG-18 wrapper parens around an identifier that is about to be cast:
 * `(column)::TYPE` -> `column::TYPE`. Only the `(id)::` cast shape is
 * touched; function calls like `length(column)` are intentionally left
 * alone so the expression remains semantically a function call. PG-18 emits
 * CHECK expressions with explicit wrapper parens and an implicit cast
 * around column references; this helper collapses that wrapper so the
 * downstream `stripTypeCasts` and `canonicalizeAnyArrayToIn` steps can
 * match the canonical form documented in the schema manifest. The match is
 * anchored by a lookahead for `::` so the wrapper is only removed when the
 * identifier is in a cast position; without the lookahead, `(col)` inside
 * a function call would be wrongly stripped.
 */
function stripCastWrap(value: string): string {
  let prev: string;
  do {
    prev = value;
    value = value.replace(/\(\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*\)\s*(?=::)/g, '$1');
  } while (value !== prev);
  return value;
}

/**
 * Strip redundant double quotes around identifiers that PostgreSQL quotes
 * ONLY because they collide with a reserved keyword (e.g. `"position"`,
 * `"length"`). A quoted identifier `"<id>"` is collapsed to bare `<id>`
 * ONLY when its content is a simple, already-lowercase, ASCII identifier
 * matching `[a-zA-Z_][a-zA-Z0-9_]*` — i.e. one that PG could legally
 * write unquoted without changing meaning. The regex explicitly handles
 * the doubled-quote escape form `"a""b"` by recognizing a single
 * embedded `""` (and PRESERVING the whole token in that case so the
 * outer pair does not get stripped around only the inner identifier).
 *
 * Preserved (NOT weakened):
 *  - Case-sensitive identifiers: `"Position"`, `"MyColumn"`, `"ALL_CAPS"`.
 *  - Identifiers with non-identifier characters: `"my column"`,
 *    `"col-with-dash"`, `"col.with.dots"`, `"special$char"`.
 *  - Escaped-quote identifiers: `"col""name"` — the optional inner
 *    `""name` segment is captured; if present the whole match is
 *    returned untouched so the escape structure is preserved.
 *  - The empty string `""` (regex requires at least one identifier char).
 *
 * The stripper runs BEFORE `lowercase` so that a case-sensitive quoted
 * identifier (which would be lowercased to its lowercase form) keeps its
 * quotes intact, preserving the distinction between `position` (bare,
 * case-insensitive, equals `"POSITION"`, `"Position"`, etc.) and
 * `"Position"` (case-sensitive quoted — a different PG identifier).
 */
function stripRedundantDoubleQuotes(value: string): string {
  return value.replace(
    /"([a-zA-Z_][a-zA-Z0-9_]*)(?:""([a-zA-Z_][a-zA-Z0-9_]*))?"/g,
    (match, id1: string, id2?: string) => {
      if (id2 !== undefined) {
        // Escaped-quote identifier: the outer pair is NOT keyword-quoting,
        // it is structural. Preserve the whole match untouched.
        return match;
      }
      return id1 === id1.toLowerCase() ? id1 : match;
    },
  );
}

function stripOuterParentheses(value: string): string {
  let s = value.trim();
  while (s.startsWith('(') && s.endsWith(')')) {
    const inner = s.slice(1, -1).trim();
    // Stop if the inner text has unbalanced parentheses.
    let depth = 0;
    let balanced = true;
    for (const ch of inner) {
      if (ch === '(') depth += 1;
      if (ch === ')') {
        depth -= 1;
        if (depth < 0) {
          balanced = false;
          break;
        }
      }
    }
    if (!balanced || depth !== 0) break;
    s = inner;
  }
  return s;
}

/**
 * Splits `value` by `delimiter` only at the top nesting level (parentheses and
 * square brackets are tracked; string literals are skipped). Used to parse
 * expression lists and boolean chains deterministically.
 */
function splitTopLevel(value: string, delimiter: string): string[] {
  const result: string[] = [];
  let current = '';
  let depth = 0;
  let inString: string | null = null;
  const lowerDelimiter = delimiter.toLowerCase();
  let i = 0;
  while (i < value.length) {
    const ch = value[i];
    if (inString !== null) {
      current += ch;
      if (ch === inString) {
        // Doubled quote is an escaped quote inside the literal.
        if (i + 1 < value.length && value[i + 1] === inString) {
          current += value[i + 1];
          i += 2;
          continue;
        }
        inString = null;
      }
      i += 1;
      continue;
    }
    if (ch === "'" || ch === '"') {
      inString = ch;
      current += ch;
      i += 1;
      continue;
    }
    if (ch === '(' || ch === '[') {
      depth += 1;
    } else if (ch === ')' || ch === ']') {
      depth -= 1;
    }
    if (depth === 0 && value.slice(i, i + delimiter.length).toLowerCase() === lowerDelimiter) {
      result.push(current);
      current = '';
      i += delimiter.length;
      continue;
    }
    current += ch;
    i += 1;
  }
  result.push(current);
  return result;
}

/**
 * Canonicalises PostgreSQL's `x = ANY (ARRAY[...])` form back to the equivalent
 * `x IN (...)` form. Both are deterministic and preserve every value, operator
 * and column; only the textual representation is normalised.
 */
function canonicalizeAnyArrayToIn(definition: string): string {
  return definition.replace(
    /\b([a-z_][a-z0-9_$]*)\s*=\s*any\s*\(\s*array\s*\[(.+?)\]\s*\)/gi,
    (_match, expr: string, itemsRaw: string) => {
      const items = splitTopLevel(itemsRaw, ',')
        .map((item) => collapseWhitespace(item))
        .filter((item) => item !== '');
      return `${expr.toLowerCase()} in (${items.join(', ')})`;
    },
  );
}

const VARCHAR_STRING_LITERAL = /^('(?:[^']|'')*')::character varying$/;

/**
 * For a varchar column, `col IN ('a', 'b')` is rendered by PG as
 * `(col)::text = ANY ((ARRAY['a'::character varying, 'b'::character varying])::text[])`.
 * Casting an array of varchar string literals to text[] only relabels each
 * element (varchar -> text is binary-coercible), so the array is rewritten
 * to `array['a', 'b']`, which `canonicalizeAnyArrayToIn` then folds into IN.
 * The rewrite applies ONLY when every element is a plain string literal typed
 * `character varying` and the array cast is exactly `::text[]`; any other
 * element shape or cast target is left untouched (fail closed). The operator
 * (`= any`, `<> all`, ...) is never touched here.
 */
function canonicalizeVarcharLiteralArray(definition: string): string {
  return definition.replace(
    /\(\s*array\s*\[([^\]]*)\]\s*\)::text\[\]/g,
    (match, itemsRaw: string) => {
      const items = splitTopLevel(itemsRaw, ',').map((item) => collapseWhitespace(item));
      const literals: string[] = [];
      for (const item of items) {
        const literal = VARCHAR_STRING_LITERAL.exec(item);
        if (literal === null) return match;
        literals.push(literal[1]!);
      }
      return `array[${literals.join(', ')}]`;
    },
  );
}

/**
 * For a varchar column, `COALESCE(col, '')` used in a text context is
 * rendered by PG as `(coalesce(col, ''::character varying))::text`.
 * varchar -> text is a binary-coercible relabel, so this equals
 * `coalesce(col, ''::text)`. Only a bare identifier plus a single string
 * literal typed `character varying` is rewritten; bpchar (which trims on
 * cast), non-literal fallbacks and any other coalesce shape are left
 * untouched. Shared by index-expression and CHECK normalization.
 */
function canonicalizeVarcharCoalesceLiteral(expression: string): string {
  return expression.replace(
    /\(\s*coalesce\(\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*,\s*('(?:[^']|'')*')::character varying\s*\)\s*\)::text\b/g,
    'coalesce($1, $2::text)',
  );
}

// ---------------------------------------------------------------------------
// Boolean-expression parser for deterministic CHECK normalisation.
//
// PostgreSQL may add redundant parentheses around OR/AND terms; the parser
// rebuilds the expression tree and re-emits it with the minimal parentheses
// required to preserve precedence. It never hides operators, columns or values.
// ---------------------------------------------------------------------------

type BooleanToken =
  | { type: 'ident'; value: string }
  | { type: 'literal'; value: string }
  | { type: 'op'; value: string }
  | { type: 'keyword'; value: string }
  | { type: 'punct'; value: string };

type BooleanExpr =
  | { type: 'or'; terms: BooleanExpr[] }
  | { type: 'and'; terms: BooleanExpr[] }
  | { type: 'not'; operand: BooleanExpr }
  | { type: 'compare'; left: BooleanExpr; op: string; right: BooleanExpr | null }
  | { type: 'in'; expr: BooleanExpr; values: BooleanExpr[] }
  | { type: 'isnull'; expr: BooleanExpr; not: boolean }
  | { type: 'ident'; value: string }
  | { type: 'literal'; value: string }
  | { type: 'func'; name: string; args: BooleanExpr[] }
  | { type: 'array'; items: BooleanExpr[] };

const BOOLEAN_KEYWORDS = new Set(['or', 'and', 'not', 'is', 'in', 'null', 'any', 'array']);

function tokenizeExpression(value: string): BooleanToken[] {
  const tokens: BooleanToken[] = [];
  let i = 0;
  while (i < value.length) {
    const ch = value[i]!;
    if (/\s/.test(ch)) {
      i += 1;
      continue;
    }
    if (ch === "'" || ch === '"') {
      let literal = ch;
      let j = i + 1;
      while (j < value.length) {
        const c = value[j]!;
        literal += c;
        if (c === ch) {
          if (value[j + 1] === ch) {
            literal += ch;
            j += 2;
            continue;
          }
          break;
        }
        j += 1;
      }
      tokens.push({ type: 'literal', value: literal });
      i = j + 1;
      continue;
    }
    if (/[a-z_]/i.test(ch)) {
      let ident = ch;
      let j = i + 1;
      while (j < value.length && /[a-z0-9_$]/i.test(value[j]!)) {
        ident += value[j]!;
        j += 1;
      }
      const lower = ident.toLowerCase();
      tokens.push(
        BOOLEAN_KEYWORDS.has(lower)
          ? { type: 'keyword', value: lower }
          : { type: 'ident', value: lower },
      );
      i = j;
      continue;
    }
    if (/[0-9]/.test(ch) || (ch === '-' && /[0-9]/.test(value[i + 1] ?? ''))) {
      let num = ch;
      let j = i + 1;
      while (j < value.length && /[0-9.]/.test(value[j]!)) {
        num += value[j]!;
        j += 1;
      }
      tokens.push({ type: 'literal', value: num });
      i = j;
      continue;
    }
    if (ch === '(' || ch === ')' || ch === '[' || ch === ']' || ch === ',') {
      tokens.push({ type: 'punct', value: ch });
      i += 1;
      continue;
    }
    const two = value.slice(i, i + 2);
    if (two === '<>' || two === '>=' || two === '<=' || two === '!~') {
      tokens.push({ type: 'op', value: two });
      i += 2;
      continue;
    }
    if ('=<>~'.includes(ch)) {
      tokens.push({ type: 'op', value: ch });
      i += 1;
      continue;
    }
    throw new Error(`Unexpected character "${ch}" in CHECK expression`);
  }
  return tokens;
}

function peek(tokens: BooleanToken[]): BooleanToken | undefined {
  return tokens[0];
}

function consume(tokens: BooleanToken[]): BooleanToken {
  const token = tokens.shift();
  if (token === undefined) {
    throw new Error('Unexpected end of CHECK expression');
  }
  return token;
}

function expectPunct(tokens: BooleanToken[], value: string): void {
  const token = consume(tokens);
  if (token.type !== 'punct' || token.value !== value) {
    throw new Error(`Expected "${value}" but got "${token.value}"`);
  }
}

function parseBooleanExpression(tokens: BooleanToken[]): BooleanExpr {
  return parseOr(tokens);
}

function parseOr(tokens: BooleanToken[]): BooleanExpr {
  const terms: BooleanExpr[] = [parseAnd(tokens)];
  while (peek(tokens)?.type === 'keyword' && peek(tokens)?.value === 'or') {
    consume(tokens);
    terms.push(parseAnd(tokens));
  }
  if (terms.length === 1) return terms[0]!;
  return { type: 'or', terms };
}

function parseAnd(tokens: BooleanToken[]): BooleanExpr {
  const terms: BooleanExpr[] = [parseNot(tokens)];
  while (peek(tokens)?.type === 'keyword' && peek(tokens)?.value === 'and') {
    consume(tokens);
    terms.push(parseNot(tokens));
  }
  if (terms.length === 1) return terms[0]!;
  return { type: 'and', terms };
}

function parseNot(tokens: BooleanToken[]): BooleanExpr {
  if (peek(tokens)?.type === 'keyword' && peek(tokens)?.value === 'not') {
    consume(tokens);
    return { type: 'not', operand: parseNot(tokens) };
  }
  return parseComparison(tokens);
}

function parseComparison(tokens: BooleanToken[]): BooleanExpr {
  const left = parsePrimary(tokens);
  const next = peek(tokens);
  if (next?.type === 'op') {
    consume(tokens);
    const op = next.value;
    const right = parsePrimary(tokens);
    return { type: 'compare', left, op, right };
  }
  if (next?.type === 'keyword' && next.value === 'is') {
    consume(tokens);
    let not = false;
    if (peek(tokens)?.type === 'keyword' && peek(tokens)?.value === 'not') {
      consume(tokens);
      not = true;
    }
    if (peek(tokens)?.type === 'keyword' && peek(tokens)?.value === 'null') {
      consume(tokens);
      return { type: 'isnull', expr: left, not };
    }
    // Fall back to a generic IS comparison (not expected in migration 0001).
    return { type: 'compare', left, op: 'is', right: parsePrimary(tokens) };
  }
  if (next?.type === 'keyword' && next.value === 'in') {
    consume(tokens);
    expectPunct(tokens, '(');
    const values: BooleanExpr[] = [parseBooleanExpression(tokens)];
    while (peek(tokens)?.type === 'punct' && peek(tokens)?.value === ',') {
      consume(tokens);
      values.push(parseBooleanExpression(tokens));
    }
    expectPunct(tokens, ')');
    return { type: 'in', expr: left, values };
  }
  return left;
}

function parsePrimary(tokens: BooleanToken[]): BooleanExpr {
  const token = peek(tokens);
  if (token === undefined) {
    throw new Error('Unexpected end of CHECK expression');
  }
  if (token.type === 'ident') {
    consume(tokens);
    if (peek(tokens)?.type === 'punct' && peek(tokens)?.value === '(') {
      consume(tokens);
      const args: BooleanExpr[] = [];
      if (!(peek(tokens)?.type === 'punct' && peek(tokens)?.value === ')')) {
        args.push(parseBooleanExpression(tokens));
        while (peek(tokens)?.type === 'punct' && peek(tokens)?.value === ',') {
          consume(tokens);
          args.push(parseBooleanExpression(tokens));
        }
      }
      expectPunct(tokens, ')');
      return { type: 'func', name: token.value, args };
    }
    return { type: 'ident', value: token.value };
  }
  if (token.type === 'literal') {
    consume(tokens);
    return { type: 'literal', value: token.value };
  }
  if (token.type === 'keyword' && token.value === 'array') {
    consume(tokens);
    expectPunct(tokens, '[');
    const items: BooleanExpr[] = [parseBooleanExpression(tokens)];
    while (peek(tokens)?.type === 'punct' && peek(tokens)?.value === ',') {
      consume(tokens);
      items.push(parseBooleanExpression(tokens));
    }
    expectPunct(tokens, ']');
    return { type: 'array', items };
  }
  if (token.type === 'punct' && token.value === '(') {
    consume(tokens);
    const expr = parseBooleanExpression(tokens);
    expectPunct(tokens, ')');
    return expr;
  }
  throw new Error(`Unexpected token "${token.value}" in CHECK expression`);
}

function emitBooleanExpression(expr: BooleanExpr, parent: 'or' | 'and' | 'root' = 'root'): string {
  switch (expr.type) {
    case 'or': {
      const emitted = expr.terms.map((t) => emitBooleanExpression(t, 'or'));
      const str = emitted.join(' or ');
      if (parent === 'and') return `(${str})`;
      return str;
    }
    case 'and': {
      const emitted = expr.terms.map((t) => emitBooleanExpression(t, 'and'));
      const str = emitted.join(' and ');
      if (parent === 'or') return `(${str})`;
      return str;
    }
    case 'not':
      return `not ${emitBooleanExpression(expr.operand, 'root')}`;
    case 'compare': {
      const right = expr.right === null ? '' : ` ${emitBooleanExpression(expr.right, 'root')}`;
      return `${emitBooleanExpression(expr.left, 'root')} ${expr.op}${right}`;
    }
    case 'in':
      return `${emitBooleanExpression(expr.expr, 'root')} in (${expr.values
        .map((v) => emitBooleanExpression(v, 'root'))
        .join(', ')})`;
    case 'isnull':
      return `${emitBooleanExpression(expr.expr, 'root')} is ${expr.not ? 'not ' : ''}null`;
    case 'ident':
      return expr.value;
    case 'literal':
      return expr.value;
    case 'func':
      return `${expr.name}(${expr.args.map((a) => emitBooleanExpression(a, 'root')).join(', ')})`;
    case 'array':
      return `array[${expr.items.map((item) => emitBooleanExpression(item, 'root')).join(', ')}]`;
    default:
      return '';
  }
}

function normalizeBooleanExpression(definition: string): string {
  try {
    const tokens = tokenizeExpression(definition);
    const tree = parseBooleanExpression(tokens);
    if (tokens.length > 0) {
      throw new Error('Unexpected trailing tokens in CHECK expression');
    }
    return emitBooleanExpression(tree);
  } catch {
    // Fail closed by refusing to normalise an expression we cannot parse.
    return definition;
  }
}

export function normalizeCheckDefinition(definition: string): string {
  let s = collapseWhitespace(definition);
  s = s.replace(/^CHECK\s+/i, '');
  // Strip redundant keyword-quoting BEFORE lowercase so that
  // case-sensitive quoted identifiers (e.g. `"Position"`) keep their
  // quotes and remain distinguishable from bare `position` after the
  // lowercase step. See stripRedundantDoubleQuotes for the full contract.
  s = stripRedundantDoubleQuotes(s);
  s = lowercase(s);
  // PG varchar renderings must be canonicalized before stripTypeCasts turns
  // `::text[]` into a dangling `[]`.
  s = canonicalizeVarcharLiteralArray(s);
  s = canonicalizeVarcharCoalesceLiteral(s);
  s = stripCastWrap(s);
  s = stripTypeCasts(s);
  s = canonicalizeAnyArrayToIn(s);
  s = normalizeBooleanExpression(s);
  s = stripOuterParentheses(s);
  return s;
}

export function normalizeDefault(raw: string | null): string | null {
  if (raw === null) return null;
  let s = collapseWhitespace(raw);
  s = lowercase(s);
  s = stripTypeCasts(s);
  return s === '' ? null : s;
}

export function normalizeIndexDefinition(def: string): string {
  let s = collapseWhitespace(def);
  s = lowercase(s);
  s = stripPublicSchema(s);
  return s;
}

/**
 * Normalize a single index expression so the verifier collapses PG-18's
 * redundant `(col)::text` cast on bare column references into the bare
 * identifier. PG-18 `pg_get_indexdef` emits `lower((name)::text)` for a
 * declared `lower(name)` functional index, because `lower()` requires
 * `text` and PG shows the implicit cast as an explicit one. The cast AND
 * the redundant parentheses around the identifier are semantically a
 * no-op for character-typed columns; other casts (e.g. `::int`, `::bool`)
 * are preserved so the verifier stays fail-closed for genuinely
 * different expressions.
 *
 * Only the pattern `(<simple_identifier>)::text` is collapsed; any other
 * shape (function call with multiple args, array casts, arithmetic) is
 * returned unchanged. The function is intentionally narrow: equivalence
 * is claimed ONLY for the `(col)::text` -> `col` case (no parentheses,
 * no cast).
 *
 * One further PG-rendered variant is canonicalized: for a varchar column,
 * `lower(COALESCE(col, ''))` is emitted as
 * `lower((coalesce(col, ''::character varying))::text)`; see
 * `canonicalizeVarcharCoalesceLiteral` for the exact, narrow contract.
 */
export function normalizeIndexExpression(expression: string): string {
  return canonicalizeVarcharCoalesceLiteral(expression).replace(
    /\(\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*\)::text\b/g,
    '$1',
  );
}

// ---------------------------------------------------------------------------
// Expected manifest for migration 0001
// ---------------------------------------------------------------------------

const timestampDefault = normalizeDefault('CURRENT_TIMESTAMP');

const siteChecks: readonly CheckSpec[] = [
  { definition: normalizeCheckDefinition("btrim(code) <> ''") },
  { definition: normalizeCheckDefinition("btrim(name) <> ''") },
  {
    definition: normalizeCheckDefinition(
      "status IN ('provisioning', 'active', 'migrating', 'degraded', 'disabled')",
    ),
  },
  { definition: normalizeCheckDefinition('updated_at >= created_at') },
];

const userChecks: readonly CheckSpec[] = [
  { definition: normalizeCheckDefinition("btrim(email) <> ''") },
  { definition: normalizeCheckDefinition("btrim(full_name) <> ''") },
  { definition: normalizeCheckDefinition("btrim(password_hash) <> ''") },
  { definition: normalizeCheckDefinition("status IN ('active', 'disabled')") },
  { definition: normalizeCheckDefinition('security_version >= 0') },
  { definition: normalizeCheckDefinition('updated_at >= created_at') },
];

const membershipChecks: readonly CheckSpec[] = [
  { definition: normalizeCheckDefinition("role IN ('Administrador', 'Supervisor')") },
  {
    definition: normalizeCheckDefinition("status IN ('active', 'suspended', 'revoked')"),
  },
  {
    definition: normalizeCheckDefinition(
      'valid_until IS NULL OR valid_from IS NULL OR valid_until > valid_from',
    ),
  },
  { definition: normalizeCheckDefinition('updated_at >= created_at') },
];

const sessionChecks: readonly CheckSpec[] = [
  { definition: normalizeCheckDefinition("token_hash ~ '^[0-9a-f]{64}$'") },
  { definition: normalizeCheckDefinition('security_version >= 0') },
  { definition: normalizeCheckDefinition('last_seen_at >= created_at') },
  { definition: normalizeCheckDefinition('idle_expires_at > created_at') },
  { definition: normalizeCheckDefinition('absolute_expires_at > created_at') },
  { definition: normalizeCheckDefinition('idle_expires_at <= absolute_expires_at') },
  { definition: normalizeCheckDefinition('revoked_at IS NULL OR revoked_at >= created_at') },
  { definition: normalizeCheckDefinition('revoked_at IS NULL OR revocation_reason IS NOT NULL') },
  {
    definition: normalizeCheckDefinition(
      "revocation_reason IS NULL OR btrim(revocation_reason) <> ''",
    ),
  },
];

export const IDENTITY_CONTROL_PLANE_SCHEMA_MANIFEST: SchemaManifest = {
  schema: 'public',
  tables: {
    lu_site: {
      columns: [
        {
          name: 'id',
          dataType: 'uuid',
          udtName: 'uuid',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'code',
          dataType: 'text',
          udtName: 'text',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'name',
          dataType: 'text',
          udtName: 'text',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'status',
          dataType: 'text',
          udtName: 'text',
          charMaxLength: null,
          isNullable: false,
          columnDefault: normalizeDefault("'provisioning'::text"),
        },
        {
          name: 'created_at',
          dataType: 'timestamp with time zone',
          udtName: 'timestamptz',
          charMaxLength: null,
          isNullable: false,
          columnDefault: timestampDefault,
        },
        {
          name: 'updated_at',
          dataType: 'timestamp with time zone',
          udtName: 'timestamptz',
          charMaxLength: null,
          isNullable: false,
          columnDefault: timestampDefault,
        },
      ],
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: siteChecks,
      indexes: [
        { name: 'lu_site_pkey', table: 'lu_site', columns: ['id'], unique: true, where: null },
        {
          name: 'ux_lu_site_code_lower',
          table: 'lu_site',
          columns: ['lower(code)'],
          unique: true,
          where: null,
        },
      ],
    },
    lu_user: {
      columns: [
        {
          name: 'id',
          dataType: 'uuid',
          udtName: 'uuid',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'email',
          dataType: 'text',
          udtName: 'text',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'full_name',
          dataType: 'text',
          udtName: 'text',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'password_hash',
          dataType: 'text',
          udtName: 'text',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'is_super_admin',
          dataType: 'boolean',
          udtName: 'bool',
          charMaxLength: null,
          isNullable: false,
          columnDefault: normalizeDefault('false'),
        },
        {
          name: 'status',
          dataType: 'text',
          udtName: 'text',
          charMaxLength: null,
          isNullable: false,
          columnDefault: normalizeDefault("'active'::text"),
        },
        {
          name: 'security_version',
          dataType: 'bigint',
          udtName: 'int8',
          charMaxLength: null,
          isNullable: false,
          columnDefault: normalizeDefault('0'),
        },
        {
          name: 'created_at',
          dataType: 'timestamp with time zone',
          udtName: 'timestamptz',
          charMaxLength: null,
          isNullable: false,
          columnDefault: timestampDefault,
        },
        {
          name: 'updated_at',
          dataType: 'timestamp with time zone',
          udtName: 'timestamptz',
          charMaxLength: null,
          isNullable: false,
          columnDefault: timestampDefault,
        },
      ],
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: userChecks,
      indexes: [
        { name: 'lu_user_pkey', table: 'lu_user', columns: ['id'], unique: true, where: null },
        {
          name: 'ux_lu_user_email_lower',
          table: 'lu_user',
          columns: ['lower(email)'],
          unique: true,
          where: null,
        },
      ],
    },
    lu_site_membership: {
      columns: [
        {
          name: 'user_id',
          dataType: 'uuid',
          udtName: 'uuid',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'site_id',
          dataType: 'uuid',
          udtName: 'uuid',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'role',
          dataType: 'text',
          udtName: 'text',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'status',
          dataType: 'text',
          udtName: 'text',
          charMaxLength: null,
          isNullable: false,
          columnDefault: normalizeDefault("'active'::text"),
        },
        {
          name: 'valid_from',
          dataType: 'timestamp with time zone',
          udtName: 'timestamptz',
          charMaxLength: null,
          isNullable: true,
          columnDefault: null,
        },
        {
          name: 'valid_until',
          dataType: 'timestamp with time zone',
          udtName: 'timestamptz',
          charMaxLength: null,
          isNullable: true,
          columnDefault: null,
        },
        {
          name: 'created_at',
          dataType: 'timestamp with time zone',
          udtName: 'timestamptz',
          charMaxLength: null,
          isNullable: false,
          columnDefault: timestampDefault,
        },
        {
          name: 'updated_at',
          dataType: 'timestamp with time zone',
          udtName: 'timestamptz',
          charMaxLength: null,
          isNullable: false,
          columnDefault: timestampDefault,
        },
      ],
      primaryKey: { columns: ['user_id', 'site_id'] },
      uniques: [],
      foreignKeys: [
        {
          columns: ['user_id'],
          referencesTable: 'lu_user',
          referencesColumns: ['id'],
          deleteAction: 'RESTRICT',
        },
        {
          columns: ['site_id'],
          referencesTable: 'lu_site',
          referencesColumns: ['id'],
          deleteAction: 'RESTRICT',
        },
      ],
      checks: membershipChecks,
      indexes: [
        {
          name: 'lu_site_membership_pkey',
          table: 'lu_site_membership',
          columns: ['user_id', 'site_id'],
          unique: true,
          where: null,
        },
        {
          name: 'ix_lu_site_membership_site_status',
          table: 'lu_site_membership',
          columns: ['site_id', 'status'],
          unique: false,
          where: null,
        },
      ],
    },
    lu_session: {
      columns: [
        {
          name: 'id',
          dataType: 'uuid',
          udtName: 'uuid',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'token_hash',
          dataType: 'character',
          udtName: 'bpchar',
          charMaxLength: 64,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'user_id',
          dataType: 'uuid',
          udtName: 'uuid',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'active_site_id',
          dataType: 'uuid',
          udtName: 'uuid',
          charMaxLength: null,
          isNullable: true,
          columnDefault: null,
        },
        {
          name: 'security_version',
          dataType: 'bigint',
          udtName: 'int8',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'created_at',
          dataType: 'timestamp with time zone',
          udtName: 'timestamptz',
          charMaxLength: null,
          isNullable: false,
          columnDefault: timestampDefault,
        },
        {
          name: 'last_seen_at',
          dataType: 'timestamp with time zone',
          udtName: 'timestamptz',
          charMaxLength: null,
          isNullable: false,
          columnDefault: timestampDefault,
        },
        {
          name: 'idle_expires_at',
          dataType: 'timestamp with time zone',
          udtName: 'timestamptz',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'absolute_expires_at',
          dataType: 'timestamp with time zone',
          udtName: 'timestamptz',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'revoked_at',
          dataType: 'timestamp with time zone',
          udtName: 'timestamptz',
          charMaxLength: null,
          isNullable: true,
          columnDefault: null,
        },
        {
          name: 'revocation_reason',
          dataType: 'text',
          udtName: 'text',
          charMaxLength: null,
          isNullable: true,
          columnDefault: null,
        },
      ],
      primaryKey: { columns: ['id'] },
      uniques: [{ columns: ['token_hash'] }],
      foreignKeys: [
        {
          columns: ['user_id'],
          referencesTable: 'lu_user',
          referencesColumns: ['id'],
          deleteAction: 'RESTRICT',
        },
        {
          columns: ['active_site_id'],
          referencesTable: 'lu_site',
          referencesColumns: ['id'],
          deleteAction: 'RESTRICT',
        },
      ],
      checks: sessionChecks,
      indexes: [
        {
          name: 'lu_session_pkey',
          table: 'lu_session',
          columns: ['id'],
          unique: true,
          where: null,
        },
        {
          name: 'lu_session_token_hash_key',
          table: 'lu_session',
          columns: ['token_hash'],
          unique: true,
          where: null,
        },
        {
          name: 'ix_lu_session_user',
          table: 'lu_session',
          columns: ['user_id'],
          unique: false,
          where: null,
        },
        {
          name: 'ix_lu_session_active_expiry',
          table: 'lu_session',
          columns: ['absolute_expires_at', 'idle_expires_at'],
          unique: false,
          where: normalizeCheckDefinition('revoked_at IS NULL'),
        },
      ],
    },
  },
};

const rateLimitChecks: readonly CheckSpec[] = [
  { definition: normalizeCheckDefinition("scope IN ('email_ip', 'ip')") },
  { definition: normalizeCheckDefinition("key_hash ~ '^[0-9a-f]{64}$'") },
  { definition: normalizeCheckDefinition('attempt_count >= 1') },
  { definition: normalizeCheckDefinition('reset_at > window_started_at') },
  { definition: normalizeCheckDefinition('updated_at >= window_started_at') },
];

const securityEventChecks: readonly CheckSpec[] = [
  {
    definition: normalizeCheckDefinition(
      "event_type IN ('login_success', 'login_failure', 'login_rate_limited', 'logout', 'active_site_changed', 'admin_bootstrap')",
    ),
  },
  {
    definition: normalizeCheckDefinition("subject_hash IS NULL OR subject_hash ~ '^[0-9a-f]{64}$'"),
  },
  {
    definition: normalizeCheckDefinition("ip_hash IS NULL OR ip_hash ~ '^[0-9a-f]{64}$'"),
  },
  { definition: normalizeCheckDefinition('user_id IS NOT NULL OR subject_hash IS NOT NULL') },
  { definition: normalizeCheckDefinition("jsonb_typeof(metadata) = 'object'") },
];

/** Final schema expected after applying registered migrations 0001 and 0002. */
export const AUTH_SECURITY_SCHEMA_MANIFEST: SchemaManifest<
  Exclude<ControlPlaneTable, 'lu_tenant_route'>
> = {
  schema: 'public',
  tables: {
    ...IDENTITY_CONTROL_PLANE_SCHEMA_MANIFEST.tables,
    lu_auth_rate_limit: {
      columns: [
        {
          name: 'scope',
          dataType: 'text',
          udtName: 'text',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'key_hash',
          dataType: 'character',
          udtName: 'bpchar',
          charMaxLength: 64,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'attempt_count',
          dataType: 'integer',
          udtName: 'int4',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'window_started_at',
          dataType: 'timestamp with time zone',
          udtName: 'timestamptz',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'reset_at',
          dataType: 'timestamp with time zone',
          udtName: 'timestamptz',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'updated_at',
          dataType: 'timestamp with time zone',
          udtName: 'timestamptz',
          charMaxLength: null,
          isNullable: false,
          columnDefault: timestampDefault,
        },
      ],
      primaryKey: { columns: ['scope', 'key_hash'] },
      uniques: [],
      foreignKeys: [],
      checks: rateLimitChecks,
      indexes: [
        {
          name: 'pk_lu_auth_rate_limit',
          table: 'lu_auth_rate_limit',
          columns: ['scope', 'key_hash'],
          unique: true,
          where: null,
        },
        {
          name: 'ix_lu_auth_rate_limit_reset',
          table: 'lu_auth_rate_limit',
          columns: ['reset_at'],
          unique: false,
          where: null,
        },
      ],
    },
    lu_security_event: {
      columns: [
        {
          name: 'id',
          dataType: 'uuid',
          udtName: 'uuid',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'event_type',
          dataType: 'text',
          udtName: 'text',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'user_id',
          dataType: 'uuid',
          udtName: 'uuid',
          charMaxLength: null,
          isNullable: true,
          columnDefault: null,
        },
        {
          name: 'site_id',
          dataType: 'uuid',
          udtName: 'uuid',
          charMaxLength: null,
          isNullable: true,
          columnDefault: null,
        },
        {
          name: 'subject_hash',
          dataType: 'character',
          udtName: 'bpchar',
          charMaxLength: 64,
          isNullable: true,
          columnDefault: null,
        },
        {
          name: 'ip_hash',
          dataType: 'character',
          udtName: 'bpchar',
          charMaxLength: 64,
          isNullable: true,
          columnDefault: null,
        },
        {
          name: 'occurred_at',
          dataType: 'timestamp with time zone',
          udtName: 'timestamptz',
          charMaxLength: null,
          isNullable: false,
          columnDefault: timestampDefault,
        },
        {
          name: 'metadata',
          dataType: 'jsonb',
          udtName: 'jsonb',
          charMaxLength: null,
          isNullable: false,
          columnDefault: normalizeDefault("'{}'::jsonb"),
        },
      ],
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [
        {
          columns: ['user_id'],
          referencesTable: 'lu_user',
          referencesColumns: ['id'],
          deleteAction: 'RESTRICT',
        },
        {
          columns: ['site_id'],
          referencesTable: 'lu_site',
          referencesColumns: ['id'],
          deleteAction: 'RESTRICT',
        },
      ],
      checks: securityEventChecks,
      indexes: [
        {
          name: 'pk_lu_security_event',
          table: 'lu_security_event',
          columns: ['id'],
          unique: true,
          where: null,
        },
        {
          name: 'ix_lu_security_event_type_time',
          table: 'lu_security_event',
          columns: ['event_type', 'occurred_at'],
          unique: false,
          where: null,
        },
        {
          name: 'ix_lu_security_event_user_time',
          table: 'lu_security_event',
          columns: ['user_id', 'occurred_at'],
          unique: false,
          where: normalizeCheckDefinition('user_id IS NOT NULL'),
        },
      ],
    },
  },
};

const tenantRouteChecks: readonly CheckSpec[] = [
  {
    definition: normalizeCheckDefinition(
      "runtime_secret_reference ~ '^[A-Za-z][A-Za-z0-9._/-]{2,127}$' AND runtime_secret_reference !~ '\\.\\.'",
    ),
  },
  {
    definition: normalizeCheckDefinition(
      "writer_label IN ('LEGACY_SQLSERVER', 'NEST_SQLSERVER', 'NEST_POSTGRES')",
    ),
  },
  {
    definition: normalizeCheckDefinition(
      "state IN ('active', 'migrating', 'degraded', 'disabled')",
    ),
  },
  { definition: normalizeCheckDefinition('schema_version >= 0') },
  { definition: normalizeCheckDefinition('updated_at >= created_at') },
];

/** Final control-plane schema expected after registered migrations 0001-0003. */
export const TENANT_ROUTE_SCHEMA_MANIFEST: SchemaManifest<ControlPlaneTable> = {
  schema: 'public',
  tables: {
    ...AUTH_SECURITY_SCHEMA_MANIFEST.tables,
    lu_tenant_route: {
      columns: [
        {
          name: 'site_id',
          dataType: 'uuid',
          udtName: 'uuid',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'runtime_secret_reference',
          dataType: 'text',
          udtName: 'text',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'writer_label',
          dataType: 'text',
          udtName: 'text',
          charMaxLength: null,
          isNullable: false,
          columnDefault: null,
        },
        {
          name: 'state',
          dataType: 'text',
          udtName: 'text',
          charMaxLength: null,
          isNullable: false,
          columnDefault: normalizeDefault("'migrating'::text"),
        },
        {
          name: 'schema_version',
          dataType: 'integer',
          udtName: 'int4',
          charMaxLength: null,
          isNullable: false,
          columnDefault: normalizeDefault('0'),
        },
        {
          name: 'last_health_at',
          dataType: 'timestamp with time zone',
          udtName: 'timestamptz',
          charMaxLength: null,
          isNullable: true,
          columnDefault: null,
        },
        {
          name: 'created_at',
          dataType: 'timestamp with time zone',
          udtName: 'timestamptz',
          charMaxLength: null,
          isNullable: false,
          columnDefault: timestampDefault,
        },
        {
          name: 'updated_at',
          dataType: 'timestamp with time zone',
          udtName: 'timestamptz',
          charMaxLength: null,
          isNullable: false,
          columnDefault: timestampDefault,
        },
      ],
      primaryKey: { columns: ['site_id'] },
      uniques: [],
      foreignKeys: [
        {
          columns: ['site_id'],
          referencesTable: 'lu_site',
          referencesColumns: ['id'],
          deleteAction: 'RESTRICT',
        },
      ],
      checks: tenantRouteChecks,
      indexes: [
        {
          name: 'pk_lu_tenant_route',
          table: 'lu_tenant_route',
          columns: ['site_id'],
          unique: true,
          where: null,
        },
        {
          name: 'ux_lu_tenant_route_secret_reference',
          table: 'lu_tenant_route',
          columns: ['runtime_secret_reference'],
          unique: true,
          where: null,
        },
        {
          name: 'ix_lu_tenant_route_state',
          table: 'lu_tenant_route',
          columns: ['state'],
          unique: false,
          where: null,
        },
      ],
    },
  },
};

// ---------------------------------------------------------------------------
// Catalog queries
// ---------------------------------------------------------------------------

interface ColumnRow extends Record<string, unknown> {
  table_name: string;
  column_name: string;
  data_type: string;
  udt_name: string;
  character_maximum_length: number | null;
  is_nullable: string;
  column_default: string | null;
  /**
   * `pg_attribute.attidentity`: `'d'` (BY DEFAULT IDENTITY), `'a'` (ALWAYS
   * IDENTITY) or empty string (non-identity). Always present as an empty
   * string in the projected row, never NULL, so the verifier can rely on
   * `=== 'd'` checks without nullability.
   */
  attidentity: string;
}

interface ConstraintRow extends Record<string, unknown> {
  table_name: string;
  constraint_name: string;
  constraint_type: string;
  definition: string | null;
}

interface IndexRow extends Record<string, unknown> {
  index_name: string;
  table_name: string;
  indexdef: string;
}

async function queryRows<T extends Record<string, unknown>>(
  client: Client,
  text: string,
  values?: unknown[],
): Promise<T[]> {
  const result = values
    ? await client.query<T>(text, values as never[])
    : await client.query<T>(text);
  return (result.rows as T[]) ?? [];
}

function buildMap<K, V>(): Map<K, V[]> {
  return new Map<K, V[]>();
}

function pushToMap<K, V>(map: Map<K, V[]>, key: K, value: V): void {
  const list = map.get(key);
  if (list === undefined) {
    map.set(key, [value]);
  } else {
    list.push(value);
  }
}

// ---------------------------------------------------------------------------
// Verification
// ---------------------------------------------------------------------------

export async function verifySchema<TTable extends string>(
  client: Client,
  manifest: SchemaManifest<TTable>,
): Promise<SchemaVerification> {
  const diffs: string[] = [];
  const expectedTables = Object.keys(manifest.tables) as TTable[];

  // Columns
  const colRows = await queryRows<ColumnRow>(
    client,
    `SELECT c.table_name, c.column_name, c.data_type, c.udt_name,
            c.character_maximum_length, c.is_nullable, c.column_default,
            COALESCE(a.attidentity, '') AS attidentity
     FROM information_schema.columns c
     JOIN pg_class cls ON cls.relname = c.table_name
     JOIN pg_namespace n
       ON n.oid = cls.relnamespace AND n.nspname = c.table_schema
     JOIN pg_attribute a
       ON a.attrelid = cls.oid AND a.attname = c.column_name
     WHERE c.table_schema = $1 AND c.table_name = ANY($2::text[])
       AND a.attnum > 0 AND NOT a.attisdropped
     ORDER BY c.table_name, c.ordinal_position`,
    [manifest.schema, [...expectedTables]],
  );

  const actualColumns = buildMap<string, ColumnSpec>();
  const actualIdentity = new Map<string, string>();
  for (const row of colRows) {
    pushToMap(actualColumns, row.table_name, {
      name: row.column_name,
      dataType: row.data_type,
      udtName: row.udt_name,
      charMaxLength: row.character_maximum_length,
      isNullable: row.is_nullable === 'YES',
      columnDefault: normalizeDefault(row.column_default),
    });
    actualIdentity.set(`${row.table_name}.${row.column_name}`, row.attidentity);
  }

  for (const table of expectedTables) {
    const expected = manifest.tables[table];
    if (expected === undefined) continue;
    const actualList = actualColumns.get(table) ?? [];

    const actualByName = new Map(actualList.map((c) => [c.name, c]));
    for (const expectedCol of expected.columns) {
      const actualCol = actualByName.get(expectedCol.name);
      if (actualCol === undefined) {
        diffs.push(`${table}.${expectedCol.name}: column is missing`);
        continue;
      }
      if (actualCol.dataType !== expectedCol.dataType) {
        diffs.push(
          `${table}.${expectedCol.name}: expected data_type ${expectedCol.dataType}, got ${actualCol.dataType}`,
        );
      }
      if (actualCol.udtName !== expectedCol.udtName) {
        diffs.push(
          `${table}.${expectedCol.name}: expected udt_name ${expectedCol.udtName}, got ${actualCol.udtName}`,
        );
      }
      if (actualCol.charMaxLength !== expectedCol.charMaxLength) {
        diffs.push(
          `${table}.${expectedCol.name}: expected char_max_length ${expectedCol.charMaxLength}, got ${actualCol.charMaxLength}`,
        );
      }
      if (actualCol.isNullable !== expectedCol.isNullable) {
        diffs.push(
          `${table}.${expectedCol.name}: expected nullable ${expectedCol.isNullable}, got ${actualCol.isNullable}`,
        );
      }
      // Identity columns: PG omits the nextval default from
      // information_schema.columns.column_default; identity is encoded in
      // pg_attribute.attidentity. When the manifest declares an identity
      // column we MUST see columnDefault = NULL AND attidentity = 'd'
      // (BY DEFAULT). For non-identity columns we still compare the
      // columnDefault string as before.
      if (expectedCol.identity !== undefined) {
        if (actualCol.columnDefault !== null) {
          diffs.push(
            `${table}.${expectedCol.name}: expected identity column (default null), got column_default ${actualCol.columnDefault ?? 'null'}`,
          );
        }
        const actualAttidentity = actualIdentity.get(`${table}.${expectedCol.name}`) ?? '';
        if (actualAttidentity !== 'd') {
          diffs.push(
            `${table}.${expectedCol.name}: expected attidentity='d' (GENERATED BY DEFAULT AS IDENTITY), got '${actualAttidentity}'`,
          );
        }
      } else if (actualCol.columnDefault !== expectedCol.columnDefault) {
        diffs.push(
          `${table}.${expectedCol.name}: expected default ${expectedCol.columnDefault ?? 'null'}, got ${actualCol.columnDefault ?? 'null'}`,
        );
      }
    }
    const expectedNames = new Set(expected.columns.map((c) => c.name));
    for (const actualCol of actualList) {
      if (!expectedNames.has(actualCol.name)) {
        diffs.push(`${table}.${actualCol.name}: unexpected extra column`);
      }
    }
  }

  // Constraints (PK, unique, FK, check) via pg_get_constraintdef.
  const conRows = await queryRows<ConstraintRow>(
    client,
    `SELECT cls.relname AS table_name,
            con.conname AS constraint_name,
            con.contype AS constraint_type,
            pg_get_constraintdef(con.oid) AS definition
     FROM pg_constraint con
     JOIN pg_class cls ON cls.oid = con.conrelid
     JOIN pg_namespace ns ON ns.oid = cls.relnamespace
     WHERE ns.nspname = $1 AND cls.relname = ANY($2::text[])
       AND con.contype IN ('p', 'u', 'f', 'c')`,
    [manifest.schema, [...expectedTables]],
  );

  const actualConstraints = buildMap<string, string>();
  for (const row of conRows) {
    const def = row.definition ?? '';
    pushToMap(actualConstraints, row.table_name, def);
  }

  for (const table of expectedTables) {
    const expected = manifest.tables[table];
    if (expected === undefined) continue;
    const rawDefs = actualConstraints.get(table) ?? [];

    const pkDefs: string[] = [];
    const uniqueDefs: string[] = [];
    const fkDefs: string[] = [];
    const checkDefs: string[] = [];

    for (const def of rawDefs) {
      const normalized = collapseWhitespace(def).toLowerCase();
      if (normalized.startsWith('primary key')) pkDefs.push(normalizePrimaryKey(def));
      else if (normalized.startsWith('unique')) uniqueDefs.push(normalizeUnique(def));
      else if (normalized.startsWith('foreign key')) fkDefs.push(normalizeForeignKey(def));
      else if (normalized.startsWith('check')) checkDefs.push(normalizeCheckDefinition(def));
    }

    const expectedPk = normalizePrimaryKey(
      `PRIMARY KEY (${expected.primaryKey.columns.join(', ')})`,
    );
    if (!pkDefs.includes(expectedPk)) {
      diffs.push(`${table}: missing PRIMARY KEY (${expected.primaryKey.columns.join(', ')})`);
    }

    const expectedUniqueSet = new Set(
      expected.uniques.map((u) => normalizeUnique(`UNIQUE (${u.columns.join(', ')})`)),
    );
    for (const expectedUnique of expectedUniqueSet) {
      if (!uniqueDefs.includes(expectedUnique)) {
        diffs.push(`${table}: missing UNIQUE ${expectedUnique}`);
      }
    }
    for (const actualUnique of uniqueDefs) {
      if (!expectedUniqueSet.has(actualUnique)) {
        diffs.push(`${table}: unexpected UNIQUE ${actualUnique}`);
      }
    }

    const expectedFkSet = new Set(
      expected.foreignKeys.map((fk) =>
        normalizeForeignKey(
          `FOREIGN KEY (${fk.columns.join(', ')}) REFERENCES ${fk.referencesTable}(${fk.referencesColumns.join(', ')}) ON DELETE ${fk.deleteAction}`,
        ),
      ),
    );
    for (const expectedFk of expectedFkSet) {
      if (!fkDefs.includes(expectedFk)) {
        diffs.push(`${table}: missing FOREIGN KEY ${expectedFk}`);
      }
    }
    for (const actualFk of fkDefs) {
      if (!expectedFkSet.has(actualFk)) {
        diffs.push(`${table}: unexpected FOREIGN KEY ${actualFk}`);
      }
    }

    const expectedCheckSet = new Set(expected.checks.map((c) => c.definition));
    for (const expectedCheck of expectedCheckSet) {
      if (!checkDefs.includes(expectedCheck)) {
        diffs.push(`${table}: missing CHECK ${expectedCheck}`);
      }
    }
    for (const actualCheck of checkDefs) {
      if (!expectedCheckSet.has(actualCheck)) {
        diffs.push(`${table}: unexpected CHECK ${actualCheck}`);
      }
    }
  }

  // Indexes (explicit + implicit from PK/UNIQUE).
  const idxRows = await queryRows<IndexRow>(
    client,
    `SELECT i.relname AS index_name, t.relname AS table_name, pg_get_indexdef(i.oid) AS indexdef
     FROM pg_index ix
     JOIN pg_class i ON i.oid = ix.indexrelid
     JOIN pg_class t ON t.oid = ix.indrelid
     JOIN pg_namespace n ON n.oid = t.relnamespace
     WHERE n.nspname = $1 AND t.relname = ANY($2::text[])`,
    [manifest.schema, [...expectedTables]],
  );

  const actualIndexes = buildMap<string, IndexSpec>();
  const unparseableIndexes = buildMap<string, { name: string; definition: string }>();
  for (const row of idxRows) {
    const parsed = parseIndexDef(row.indexdef, row.table_name, row.index_name);
    if (parsed !== undefined) {
      pushToMap(actualIndexes, row.table_name, parsed);
    } else {
      pushToMap(unparseableIndexes, row.table_name, {
        name: row.index_name,
        definition: row.indexdef,
      });
    }
  }

  for (const table of expectedTables) {
    const expected = manifest.tables[table];
    if (expected === undefined) continue;
    const actualList = actualIndexes.get(table) ?? [];
    const unparseableList = unparseableIndexes.get(table) ?? [];
    const unparseableByName = new Map(unparseableList.map((u) => [u.name, u]));

    const expectedIndexSet = new Set(expected.indexes.map((i) => indexSpecKey(i)));
    const actualIndexSet = new Set(actualList.map((i) => indexSpecKey(i)));

    for (const expectedKey of expectedIndexSet) {
      if (!actualIndexSet.has(expectedKey)) {
        const expectedSpec = expected.indexes.find((i) => indexSpecKey(i) === expectedKey);
        if (expectedSpec !== undefined && unparseableByName.has(expectedSpec.name)) {
          diffs.push(`${table}: index ${expectedSpec.name} has an unparseable definition`);
        } else {
          diffs.push(`${table}: missing index ${expectedKey}`);
        }
      }
    }
    for (const actualKey of actualIndexSet) {
      if (!expectedIndexSet.has(actualKey)) {
        diffs.push(`${table}: unexpected index ${actualKey}`);
      }
    }
    for (const unparseable of unparseableList) {
      const anyExpectedWithSameName = expected.indexes.some((i) => i.name === unparseable.name);
      if (!anyExpectedWithSameName) {
        diffs.push(`${table}: unexpected unparseable index ${unparseable.name}`);
      }
    }
  }

  return {
    passed: diffs.length === 0,
    diffs,
    actualTableNames: colRows.map((r) => r.table_name).filter((v, i, a) => a.indexOf(v) === i),
  };
}

function normalizePrimaryKey(def: string): string {
  const m = /^PRIMARY\s+KEY\s*\(([^)]+)\)/i.exec(def);
  if (m === null) return collapseWhitespace(def).toLowerCase();
  return `primary key (${collapseWhitespace(m[1] ?? '').toLowerCase()})`;
}

function normalizeUnique(def: string): string {
  const m = /^UNIQUE\s*\(([^)]+)\)/i.exec(def);
  if (m === null) return collapseWhitespace(def).toLowerCase();
  return `unique (${collapseWhitespace(m[1] ?? '').toLowerCase()})`;
}

function normalizeForeignKey(def: string): string {
  let s = collapseWhitespace(def);
  s = s.replace(/^FOREIGN\s+KEY\s+/i, '');
  s = lowercase(s);
  s = stripPublicSchema(s);
  return s;
}

function indexSpecKey(spec: IndexSpec): string {
  const where = spec.where === null ? '' : ` where ${spec.where}`;
  return `${spec.unique ? 'unique ' : ''}index ${spec.name} on ${spec.table}(${spec.columns.join(', ')})${where}`;
}

function splitIndexColumns(raw: string): string[] {
  const columns: string[] = [];
  let current = '';
  let depth = 0;
  for (const ch of raw) {
    if (ch === '(') depth += 1;
    if (ch === ')') depth -= 1;
    if (ch === ',' && depth === 0) {
      columns.push(current.trim());
      current = '';
      continue;
    }
    current += ch;
  }
  if (current.trim() !== '') columns.push(current.trim());
  return columns;
}

export function parseIndexDef(def: string, table: string, name: string): IndexSpec | undefined {
  const normalized = normalizeIndexDefinition(def);

  const uniquePrefix = 'create unique index ';
  const plainPrefix = 'create index ';
  let rest: string;
  let unique = false;
  if (normalized.startsWith(uniquePrefix)) {
    unique = true;
    rest = normalized.slice(uniquePrefix.length);
  } else if (normalized.startsWith(plainPrefix)) {
    rest = normalized.slice(plainPrefix.length);
  } else {
    return undefined;
  }

  // rest: <name> on <table> using <method> (<columns>) [where <predicate>]
  const onIndex = rest.indexOf(' on ');
  if (onIndex === -1) return undefined;
  const indexName = rest.slice(0, onIndex).trim() || name;
  rest = rest.slice(onIndex + ' on '.length);

  const usingIndex = rest.indexOf(' using ');
  if (usingIndex === -1) return undefined;
  const tableName = rest.slice(0, usingIndex).trim() || table;
  rest = rest.slice(usingIndex + ' using '.length);

  // Skip the access method (e.g. btree) and find the matching '(' for the
  // column/expression list. This correctly handles functional expressions such
  // as lower(code), which contain nested parentheses.
  const colStart = rest.indexOf('(');
  if (colStart === -1) return undefined;
  let depth = 1;
  let colEnd = -1;
  for (let i = colStart + 1; i < rest.length; i += 1) {
    if (rest[i] === '(') depth += 1;
    else if (rest[i] === ')') {
      depth -= 1;
      if (depth === 0) {
        colEnd = i;
        break;
      }
    }
  }
  if (colEnd === -1) return undefined;

  const columnsRaw = rest.slice(colStart + 1, colEnd);
  const afterColumns = rest.slice(colEnd + 1).trim();
  let whereRaw: string | null = null;
  if (afterColumns.startsWith('where ')) {
    whereRaw = afterColumns.slice('where '.length).trim();
  } else if (afterColumns !== '') {
    return undefined;
  }

  return {
    name: indexName,
    table: tableName,
    columns: splitIndexColumns(columnsRaw).map((c) =>
      normalizeIndexExpression(collapseWhitespace(c).toLowerCase()),
    ),
    unique,
    where: whereRaw === null ? null : normalizeCheckDefinition(whereRaw),
  };
}
