/**
 * MIG-001-F2-W8 — exact PostgreSQL schema manifests for the tenant stream:
 * per-ordinal postcondition manifests for the immutable tenant 0001..0012 plus
 * the current 0013, and the exhaustive cumulative TENANT_FINAL_SCHEMA_MANIFEST
 * after 0013.
 *
 * Every table spec is transcribed 1:1 from the on-disk tenant SQL:
 *   - tenant/0001_dashboard_foundation.sql  (immutable)
 *   - tenant/0002_catalogs.sql              (immutable)
 *   - tenant/0003_academic_laboratories.sql (immutable; adds indexes to the
 *     0001 lu_laboratory definition — its CREATE TABLE IF NOT EXISTS is a
 *     no-op because 0001 already created the table)
 *   - tenant/0004_equipment_notes.sql       (immutable; adds indexes to the
 *     0001 lu_equipment definition)
 *   - tenant/0005_equipment_units_history.sql (immutable; adds CHECKs/index to
 *     the 0001 lu_equipment_unit definition)
 *   - tenant/0006_management_operations.sql (immutable, ACL-only)
 *   - tenant/0007_verifications.sql .. tenant/0012_people.sql (immutable)
 *   - tenant/0013_migration_history.sql     (CURRENT)
 *
 * `verifySchema` is exact and bidirectional, so every manifest below is
 * complete: no empty placeholders, no cast-only fake composition. Identity
 * columns (`GENERATED BY DEFAULT AS IDENTITY`) are represented with
 * `columnDefault = null` plus the `identity: { generated: 'BY DEFAULT',
 * sequence }` marker; PG-18 omits the nextval default from
 * `information_schema.columns.column_default` for IDENTITY columns (the
 * truth lives on `pg_attribute.attidentity='d'`) so the manifest must not
 * carry a synthetic `nextval('<seq>'::regclass)` string. Sequence
 * ownership, identity link (`pg_depend.deptype='i'`) and `attidentity='d'`
 * are carried by the supplemental structure
 * (see schema-manifest-f2.ts for the shared types).
 *
 * Control-plane-only tables never appear here: only tables the tenant SQL
 * actually creates are declared.
 *
 * Normalization notes that matter for transcription:
 *   - `BETWEEN` is written in its deparsed `>= AND <=` form because the
 *     normalizer does not parse BETWEEN and fails closed.
 *   - `IN` survives as `in (...)` via the ANY(ARRAY[...]) canonicalization.
 *   - varchar literal defaults keep their `::character varying` cast (the
 *     normalizer does not strip that cast) and are lowercased.
 *   - DESC index columns are expected as `column desc` (lowercase).
 *   - Function/COALESCE index expressions keep `::text` casts in index
 *     columns (index normalization does not strip casts).
 */
import type {
  ColumnSpec,
  CheckSpec,
  ForeignKeySpec,
  IndexSpec,
  SchemaManifest,
  TableManifest,
} from './schema-manifest.js';
import { normalizeCheckDefinition, normalizeDefault } from './schema-manifest.js';
import type { MigrationSupplementalExpectation } from './schema-manifest-f2.js';

// ---------------------------------------------------------------------------
// Column factories (duplicated here to keep the module graph acyclic:
// schema-manifest-f2.ts re-exports this module's values at runtime, so this
// file must not import runtime values back from it).
// ---------------------------------------------------------------------------

const timestampDefault = normalizeDefault('CURRENT_TIMESTAMP');
const currentDateDefault = normalizeDefault('CURRENT_DATE');

const uuidNotNull = (name: string): ColumnSpec => ({
  name,
  dataType: 'uuid',
  udtName: 'uuid',
  charMaxLength: null,
  isNullable: false,
  columnDefault: null,
});

const uuidNullable = (name: string): ColumnSpec => ({
  name,
  dataType: 'uuid',
  udtName: 'uuid',
  charMaxLength: null,
  isNullable: true,
  columnDefault: null,
});

const varchar = (
  name: string,
  length: number,
  isNullable: boolean,
  dflt: string | null,
): ColumnSpec => ({
  name,
  dataType: 'character varying',
  udtName: 'varchar',
  charMaxLength: length,
  isNullable,
  columnDefault: dflt,
});

const bool = (name: string, isNullable: boolean, dflt: string | null): ColumnSpec => ({
  name,
  dataType: 'boolean',
  udtName: 'bool',
  charMaxLength: null,
  isNullable,
  columnDefault: dflt,
});

const timestamptz = (name: string, isNullable: boolean, dflt: string | null): ColumnSpec => ({
  name,
  dataType: 'timestamp with time zone',
  udtName: 'timestamptz',
  charMaxLength: null,
  isNullable,
  columnDefault: dflt,
});

const bigint = (name: string, isNullable: boolean, dflt: string | null): ColumnSpec => ({
  name,
  dataType: 'bigint',
  udtName: 'int8',
  charMaxLength: null,
  isNullable,
  columnDefault: dflt,
});

const int4 = (name: string, isNullable: boolean, dflt: string | null): ColumnSpec => ({
  name,
  dataType: 'integer',
  udtName: 'int4',
  charMaxLength: null,
  isNullable,
  columnDefault: dflt,
});

const dateColumn = (name: string, isNullable: boolean, dflt: string | null): ColumnSpec => ({
  name,
  dataType: 'date',
  udtName: 'date',
  charMaxLength: null,
  isNullable,
  columnDefault: dflt,
});

const numericColumn = (name: string, isNullable: boolean, dflt: string | null): ColumnSpec => ({
  name,
  dataType: 'numeric',
  udtName: 'numeric',
  charMaxLength: null,
  isNullable,
  columnDefault: dflt,
});

const char = (
  name: string,
  length: number,
  isNullable: boolean,
  dflt: string | null,
): ColumnSpec => ({
  name,
  dataType: 'character',
  udtName: 'bpchar',
  charMaxLength: length,
  isNullable,
  columnDefault: dflt,
});

const identityBigint = (seqName: string): ColumnSpec => ({
  name: 'id',
  dataType: 'bigint',
  udtName: 'int8',
  charMaxLength: null,
  isNullable: false,
  columnDefault: null,
  identity: { generated: 'BY DEFAULT', sequence: seqName },
});

function checks(...definitions: readonly string[]): readonly CheckSpec[] {
  return definitions.map((definition) => ({ definition: normalizeCheckDefinition(definition) }));
}

function pkIndex(table: string, columns: readonly string[] = ['id']): IndexSpec {
  return { name: `${table}_pkey`, table, columns, unique: true, where: null };
}

// Standard audit columns shared by most tenant tables.
const auditTrailColumns = (): ColumnSpec[] => [
  uuidNullable('created_by_id'),
  timestamptz('created_at', false, timestampDefault),
  uuidNullable('updated_by_id'),
  timestamptz('updated_at', true, null),
];

// ---------------------------------------------------------------------------
// tenant 0001 — dashboard foundation
// ---------------------------------------------------------------------------

const luManagementColumns: readonly ColumnSpec[] = [
  identityBigint('lu_management_id_seq'),
  uuidNotNull('site_id'),
  int4('year', false, null),
  int4('semester', false, null),
  varchar('code', 50, false, null),
  varchar('description', 1000, true, null),
  dateColumn('start_date', true, null),
  dateColumn('planned_end_date', true, null),
  dateColumn('actual_closed_date', true, null),
  int4('status', false, normalizeDefault('0')),
  varchar('responsible', 200, true, null),
  int4('type', false, normalizeDefault('0')),
  bigint('faculty_id', true, null),
  ...auditTrailColumns(),
  bigint('row_version', false, normalizeDefault('0')),
];

const luManagementChecks: readonly CheckSpec[] = checks(
  // year BETWEEN 2000 AND 2100 (deparsed form).
  'year >= 2000 and year <= 2100',
  // semester BETWEEN 0 AND 2 (deparsed form).
  'semester >= 0 and semester <= 2',
  'status IN (0, 1, 2, 99)',
  'type IN (0, 1)',
);

const luManagementIndexes: readonly IndexSpec[] = [
  pkIndex('lu_management'),
  {
    name: 'ux_lu_management_site_code',
    table: 'lu_management',
    columns: ['site_id', 'lower(code)'],
    unique: true,
    where: null,
  },
  {
    name: 'ux_lu_management_active_type',
    table: 'lu_management',
    columns: ['site_id', 'type'],
    unique: true,
    where: normalizeCheckDefinition('status = 0'),
  },
];

const luLaboratoryColumns: readonly ColumnSpec[] = [
  identityBigint('lu_laboratory_id_seq'),
  uuidNotNull('site_id'),
  bigint('faculty_id', false, null),
  varchar('code', 20, false, null),
  varchar('name', 200, false, null),
  varchar('type', 100, true, null),
  varchar('building', 100, true, null),
  varchar('block', 50, true, null),
  varchar('floor', 50, true, null),
  varchar('room', 100, true, null),
  varchar('description', 1000, true, null),
  int4('status', false, normalizeDefault('0')),
  bigint('city_id', true, null),
  ...auditTrailColumns(),
];

const luLaboratoryChecks: readonly CheckSpec[] = checks('status IN (0, 1, 2)');

/** lu_laboratory as 0001 leaves it (before 0003 adds its indexes). */
const luLaboratory0001Indexes: readonly IndexSpec[] = [
  pkIndex('lu_laboratory'),
  {
    name: 'ux_lu_laboratory_site_code',
    table: 'lu_laboratory',
    columns: ['site_id', 'lower(code)'],
    unique: true,
    where: null,
  },
];

/** lu_laboratory final state: 0001 definition + 0003's three indexes. */
const luLaboratoryFinalIndexes: readonly IndexSpec[] = [
  ...luLaboratory0001Indexes,
  {
    name: 'ux_lu_laboratory_site_code_active',
    table: 'lu_laboratory',
    columns: ['site_id', 'lower(code)'],
    unique: true,
    where: normalizeCheckDefinition('status <> 2'),
  },
  {
    name: 'ux_lu_laboratory_site_faculty_name_active',
    table: 'lu_laboratory',
    columns: ['site_id', 'faculty_id', 'lower(name)'],
    unique: true,
    where: normalizeCheckDefinition('status <> 2'),
  },
  {
    name: 'ix_lu_laboratory_site_faculty',
    table: 'lu_laboratory',
    columns: ['site_id', 'faculty_id', 'lower(name)'],
    unique: false,
    where: null,
  },
];

const luEquipmentColumns: readonly ColumnSpec[] = [
  identityBigint('lu_equipment_id_seq'),
  uuidNotNull('site_id'),
  int4('category', false, normalizeDefault('0')),
  int4('utensil_type', true, null),
  varchar('type_classification', 200, true, null),
  int4('classification_review_status', false, normalizeDefault('0')),
  varchar('other_classification_detail', 1000, true, null),
  int4('status', false, normalizeDefault('0')),
  varchar('catalog_code', 30, true, null),
  varchar('image_url', 2000, true, null),
  bigint('country_id', true, null),
  bigint('city_id', true, null),
  varchar('name', 200, false, null),
  varchar('brand', 100, true, null),
  varchar('model', 100, true, null),
  int4('useful_life_years', true, null),
  varchar('description', 2000, true, null),
  ...auditTrailColumns(),
  bigint('row_version', false, normalizeDefault('0')),
];

const luEquipmentChecks: readonly CheckSpec[] = checks(
  'category IN (0, 1, 2)',
  'status IN (0, 1, 2)',
  // useful_life_years BETWEEN 0 AND 100 (deparsed form).
  'useful_life_years IS NULL OR (useful_life_years >= 0 and useful_life_years <= 100)',
);

/** lu_equipment as 0001 leaves it (before 0004 adds its unique indexes). */
const luEquipment0001Indexes: readonly IndexSpec[] = [
  pkIndex('lu_equipment'),
  {
    name: 'ix_lu_equipment_site_name',
    table: 'lu_equipment',
    columns: ['site_id', 'lower(name)'],
    unique: false,
    where: null,
  },
];

/** lu_equipment final state: 0001 definition + 0004's two unique indexes. */
const luEquipmentFinalIndexes: readonly IndexSpec[] = [
  ...luEquipment0001Indexes,
  {
    name: 'ux_lu_equipment_site_catalog_code_active',
    table: 'lu_equipment',
    columns: ['site_id', 'lower(catalog_code)'],
    unique: true,
    where: normalizeCheckDefinition('catalog_code IS NOT NULL AND status <> 2'),
  },
  {
    name: 'ux_lu_equipment_site_name_model_active',
    table: 'lu_equipment',
    columns: ['site_id', 'lower(name)', "lower(coalesce(model, ''::text))"],
    unique: true,
    where: normalizeCheckDefinition('status <> 2'),
  },
];

const luEquipmentUnitColumns: readonly ColumnSpec[] = [
  identityBigint('lu_equipment_unit_id_seq'),
  uuidNotNull('site_id'),
  bigint('management_id', true, null),
  bigint('equipment_id', false, null),
  bigint('laboratory_id', true, null),
  int4('location_resolution_status', false, normalizeDefault('0')),
  varchar('inventory_number', 50, false, null),
  varchar('serial_number', 100, true, null),
  bigint('career_id', true, null),
  varchar('internal_location', 200, true, null),
  dateColumn('acquisition_date', true, null),
  dateColumn('manufacturing_date', true, null),
  numericColumn('acquisition_value', true, null),
  int4('current_status', false, normalizeDefault('0')),
  int4('physical_condition', true, null),
  varchar('notes', 2000, true, null),
  ...auditTrailColumns(),
  bigint('row_version', false, normalizeDefault('0')),
];

const luEquipmentUnit0001Checks: readonly CheckSpec[] = checks(
  'acquisition_value IS NULL OR acquisition_value >= 0',
);

/** lu_equipment_unit final: 0001 checks + 0005's two added CHECKs. */
const luEquipmentUnitFinalChecks: readonly CheckSpec[] = [
  ...luEquipmentUnit0001Checks,
  ...checks(
    'current_status IN (0, 1, 2, 3, 4, 5, 6, 10, 99)',
    'location_resolution_status IN (0, 1)',
  ),
];

const luEquipmentUnit0001Indexes: readonly IndexSpec[] = [
  pkIndex('lu_equipment_unit'),
  {
    name: 'ux_lu_equipment_unit_site_inventory',
    table: 'lu_equipment_unit',
    columns: ['site_id', 'lower(inventory_number)'],
    unique: true,
    where: null,
  },
  {
    name: 'ix_lu_equipment_unit_site_lab',
    table: 'lu_equipment_unit',
    columns: ['site_id', 'laboratory_id'],
    unique: false,
    where: null,
  },
];

/** lu_equipment_unit final: 0001 indexes + 0005's site/equipment index. */
const luEquipmentUnitFinalIndexes: readonly IndexSpec[] = [
  ...luEquipmentUnit0001Indexes,
  {
    name: 'ix_lu_equipment_unit_site_equipment',
    table: 'lu_equipment_unit',
    columns: ['site_id', 'equipment_id', 'current_status'],
    unique: false,
    where: null,
  },
];

const luManagementPlanColumns: readonly ColumnSpec[] = [
  identityBigint('lu_management_plan_id_seq'),
  uuidNotNull('site_id'),
  bigint('management_id', false, null),
  bigint('maintenance_id', true, null),
  bigint('equipment_unit_id', true, null),
  bigint('verification_id', true, null),
  bigint('request_id', true, null),
  bigint('departure_id', true, null),
  bigint('kardex_history_id', true, null),
  bigint('acquisition_request_id', true, null),
  int4('current_phase', false, normalizeDefault('1')),
  int4('current_state', false, normalizeDefault('1')),
  varchar('responsible', 200, true, null),
  bigint('responsible_person_id', true, null),
  int4('planned_week', true, null),
  int4('executed_week', true, null),
  varchar('document_reference', 500, true, null),
  varchar('notes', 1000, true, null),
  timestamptz('planned_date', true, null),
  int4('plan_status', false, normalizeDefault('0')),
  bool('is_draft', false, normalizeDefault('false')),
  int4('draft_phase', true, null),
  timestamptz('draft_saved_at', true, null),
  varchar('draft_summary', 300, true, null),
  ...auditTrailColumns(),
  bigint('row_version', false, normalizeDefault('0')),
];

const luManagementPlanChecks: readonly CheckSpec[] = checks(
  // current_phase BETWEEN 1 AND 6 (deparsed).
  'current_phase >= 1 and current_phase <= 6',
  // current_state BETWEEN 1 AND 9 (deparsed).
  'current_state >= 1 and current_state <= 9',
  'plan_status IN (0, 1, 2, 3)',
  // (planned_week IS NULL OR BETWEEN 1 AND 8) AND (executed_week ...).
  '(planned_week IS NULL OR (planned_week >= 1 and planned_week <= 8)) AND (executed_week IS NULL OR (executed_week >= 1 and executed_week <= 8))',
);

const luManagementPlanIndexes: readonly IndexSpec[] = [
  pkIndex('lu_management_plan'),
  {
    name: 'ux_lu_management_plan_site_management_unit',
    table: 'lu_management_plan',
    columns: ['site_id', 'management_id', 'equipment_unit_id'],
    unique: true,
    where: normalizeCheckDefinition('equipment_unit_id IS NOT NULL'),
  },
  {
    name: 'ix_lu_management_plan_site_management_phase',
    table: 'lu_management_plan',
    columns: ['site_id', 'management_id', 'current_phase', 'current_state'],
    unique: false,
    where: null,
  },
];

const luNotificationColumns: readonly ColumnSpec[] = [
  identityBigint('lu_notification_id_seq'),
  uuidNotNull('site_id'),
  uuidNullable('user_id'),
  varchar('title', 100, false, null),
  varchar('message', 255, false, null),
  varchar('action_url', 255, true, null),
  varchar('icon_class', 50, true, null),
  bigint('management_id', true, null),
  int4('management_type', true, null),
  varchar('scope', 50, true, null),
  bool('is_read', false, normalizeDefault('false')),
  timestamptz('created_at', false, timestampDefault),
];

const luNotificationChecks: readonly CheckSpec[] = checks(
  'management_type IS NULL OR management_type IN (0, 1)',
);

const luNotificationIndexes: readonly IndexSpec[] = [
  pkIndex('lu_notification'),
  {
    name: 'ix_lu_notification_site_unread',
    table: 'lu_notification',
    columns: ['site_id', 'is_read', 'created_at desc'],
    unique: false,
    where: null,
  },
];

// ---------------------------------------------------------------------------
// tenant 0002 — catalogs
// ---------------------------------------------------------------------------

const luCountryColumns: readonly ColumnSpec[] = [
  identityBigint('lu_country_id_seq'),
  uuidNotNull('site_id'),
  varchar('name', 100, false, null),
  int4('status', false, normalizeDefault('0')),
  ...auditTrailColumns(),
];

const luCountryChecks: readonly CheckSpec[] = checks('status IN (0, 1, 2)');

const luCountryIndexes: readonly IndexSpec[] = [
  pkIndex('lu_country'),
  {
    // CONSTRAINT ux_lu_country_site_id UNIQUE (site_id, id).
    name: 'ux_lu_country_site_id',
    table: 'lu_country',
    columns: ['site_id', 'id'],
    unique: true,
    where: null,
  },
  {
    name: 'ux_lu_country_site_name_active',
    table: 'lu_country',
    columns: ['site_id', 'lower(name)'],
    unique: true,
    where: normalizeCheckDefinition('status <> 2'),
  },
];

const luCityColumns: readonly ColumnSpec[] = [
  identityBigint('lu_city_id_seq'),
  uuidNotNull('site_id'),
  bigint('country_id', false, null),
  varchar('name', 100, false, null),
  varchar('region', 100, true, null),
  int4('status', false, normalizeDefault('0')),
  ...auditTrailColumns(),
];

const luCityChecks: readonly CheckSpec[] = checks('status IN (0, 1, 2)');

const luCityForeignKeys: readonly ForeignKeySpec[] = [
  {
    columns: ['site_id', 'country_id'],
    referencesTable: 'lu_country',
    referencesColumns: ['site_id', 'id'],
    deleteAction: 'RESTRICT',
  },
];

const luCityIndexes: readonly IndexSpec[] = [
  pkIndex('lu_city'),
  {
    name: 'ux_lu_city_site_country_name_active',
    table: 'lu_city',
    columns: ['site_id', 'country_id', 'lower(name)'],
    unique: true,
    where: normalizeCheckDefinition('status <> 2'),
  },
  {
    name: 'ix_lu_city_site_country',
    table: 'lu_city',
    columns: ['site_id', 'country_id', 'lower(name)'],
    unique: false,
    where: null,
  },
];

// ---------------------------------------------------------------------------
// tenant 0004 — equipment notes
// ---------------------------------------------------------------------------

const luEquipmentNoteColumns: readonly ColumnSpec[] = [
  identityBigint('lu_equipment_note_id_seq'),
  uuidNotNull('site_id'),
  bigint('equipment_id', false, null),
  varchar('note', 500, false, null),
  uuidNullable('created_by_id'),
  timestamptz('created_at', false, timestampDefault),
];

const luEquipmentNoteForeignKeys: readonly ForeignKeySpec[] = [
  {
    columns: ['equipment_id'],
    referencesTable: 'lu_equipment',
    referencesColumns: ['id'],
    deleteAction: 'RESTRICT',
  },
];

const luEquipmentNoteIndexes: readonly IndexSpec[] = [
  pkIndex('lu_equipment_note'),
  {
    name: 'ix_lu_equipment_note_site_equipment',
    table: 'lu_equipment_note',
    columns: ['site_id', 'equipment_id', 'created_at'],
    unique: false,
    where: null,
  },
];

// ---------------------------------------------------------------------------
// tenant 0005 — equipment unit state history
// ---------------------------------------------------------------------------

const luEquipmentUnitStateHistoryColumns: readonly ColumnSpec[] = [
  identityBigint('lu_equipment_unit_state_history_id_seq'),
  uuidNotNull('site_id'),
  bigint('equipment_unit_id', false, null),
  int4('status', false, null),
  timestamptz('start_date', false, timestampDefault),
  timestamptz('end_date', true, null),
  varchar('reason', 500, true, null),
  ...auditTrailColumns(),
];

const luEquipmentUnitStateHistoryChecks: readonly CheckSpec[] = checks(
  'status IN (0, 1, 2, 3, 4, 5, 6, 10, 99)',
  'end_date IS NULL OR end_date >= start_date',
);

const luEquipmentUnitStateHistoryIndexes: readonly IndexSpec[] = [
  pkIndex('lu_equipment_unit_state_history'),
  {
    name: 'ix_lu_equipment_unit_history_site_unit_start',
    table: 'lu_equipment_unit_state_history',
    columns: ['site_id', 'equipment_unit_id', 'start_date desc', 'id desc'],
    unique: false,
    where: null,
  },
];

// ---------------------------------------------------------------------------
// tenant 0007 — verifications
// ---------------------------------------------------------------------------

const luVerificationCheckItemColumns: readonly ColumnSpec[] = [
  identityBigint('lu_verification_check_item_id_seq'),
  varchar('name', 300, false, null),
  varchar('category', 100, true, null),
  int4('display_order', false, normalizeDefault('0')),
  bool('is_active', false, normalizeDefault('true')),
  timestamptz('created_at', false, timestampDefault),
];

const luVerificationColumns: readonly ColumnSpec[] = [
  identityBigint('lu_verification_id_seq'),
  uuidNotNull('site_id'),
  bigint('equipment_unit_id', false, null),
  bigint('management_id', false, null),
  dateColumn('verification_date', false, currentDateDefault),
  varchar('observations', 2000, true, null),
  int4('physical_condition', false, null),
  int4('observed_equipment_status', true, null),
  int4('status', false, normalizeDefault('0')),
  bigint('responsible_person_id', true, null),
  ...auditTrailColumns(),
];

const luVerificationChecks: readonly CheckSpec[] = checks(
  // physical_condition BETWEEN 1 AND 5 (deparsed).
  'physical_condition >= 1 and physical_condition <= 5',
  'status IN (0, 1, 2, 3, 99)',
  'observed_equipment_status IS NULL OR observed_equipment_status IN (0, 1, 2, 3, 4, 5, 6, 10, 99)',
);

const luVerificationIndexes: readonly IndexSpec[] = [
  pkIndex('lu_verification'),
  {
    name: 'ux_lu_verification_site_management_unit',
    table: 'lu_verification',
    columns: ['site_id', 'management_id', 'equipment_unit_id'],
    unique: true,
    where: normalizeCheckDefinition('status <> 99'),
  },
  {
    name: 'ix_lu_verification_site_lab_date',
    table: 'lu_verification',
    columns: ['site_id', 'verification_date desc', 'status'],
    unique: false,
    where: null,
  },
];

const luVerificationCheckResultColumns: readonly ColumnSpec[] = [
  identityBigint('lu_verification_check_result_id_seq'),
  uuidNotNull('site_id'),
  bigint('verification_id', false, null),
  bigint('check_item_id', false, null),
  int4('result', false, normalizeDefault('0')),
];

const luVerificationCheckResultChecks: readonly CheckSpec[] = checks('result IN (0, 1)');

const luVerificationCheckResultIndexes: readonly IndexSpec[] = [
  pkIndex('lu_verification_check_result'),
  {
    // CONSTRAINT ux_lu_verification_result_item UNIQUE (verification_id, check_item_id).
    name: 'ux_lu_verification_result_item',
    table: 'lu_verification_check_result',
    columns: ['verification_id', 'check_item_id'],
    unique: true,
    where: null,
  },
];

const luVerificationFaultColumns: readonly ColumnSpec[] = [
  identityBigint('lu_verification_fault_id_seq'),
  uuidNotNull('site_id'),
  bigint('verification_id', false, null),
  varchar('description', 255, false, null),
  bool('is_deleted', false, normalizeDefault('false')),
  ...auditTrailColumns(),
];

const luVerificationFaultIndexes: readonly IndexSpec[] = [
  pkIndex('lu_verification_fault'),
  {
    name: 'ix_lu_verification_fault_site_verification',
    table: 'lu_verification_fault',
    columns: ['site_id', 'verification_id', 'is_deleted'],
    unique: false,
    where: null,
  },
];

// ---------------------------------------------------------------------------
// tenant 0008 — requests
// ---------------------------------------------------------------------------

const luRequestColumns: readonly ColumnSpec[] = [
  identityBigint('lu_request_id_seq'),
  uuidNotNull('site_id'),
  bigint('laboratory_id', true, null),
  int4('location_resolution_status', false, normalizeDefault('1')),
  bigint('import_batch_id', true, null),
  bigint('equipment_id', true, null),
  bigint('equipment_unit_id', true, null),
  bigint('management_id', false, null),
  uuidNullable('requested_by_id'),
  bigint('requested_by_person_id', true, null),
  varchar('description', 1000, false, null),
  int4('priority', false, normalizeDefault('1')),
  varchar('observations', 500, true, null),
  varchar('suggestion', 2000, true, null),
  dateColumn('request_date', true, null),
  varchar('estimated_repair_time', 100, true, null),
  int4('status', false, normalizeDefault('0')),
  uuidNullable('approved_by_id'),
  timestamptz('approval_date', true, null),
  varchar('rejection_reason', 500, true, null),
  int4('type', false, normalizeDefault('1')),
  varchar('investment_code', 50, true, null),
  varchar('cost_center', 100, true, null),
  varchar('historical_source_key', 200, true, null),
  ...auditTrailColumns(),
  bigint('row_version', false, normalizeDefault('0')),
];

const luRequestChecks: readonly CheckSpec[] = checks(
  'location_resolution_status IN (0, 1)',
  // priority BETWEEN 0 AND 3 (deparsed).
  'priority >= 0 and priority <= 3',
  'status IN (0, 1, 2, 3, 4, 5, 99)',
  'type IN (1, 2, 3)',
  'length(btrim(description)) > 0',
);

const luRequestIndexes: readonly IndexSpec[] = [
  pkIndex('lu_request'),
  {
    name: 'ix_lu_request_site_management_status',
    table: 'lu_request',
    columns: ['site_id', 'management_id', 'status', 'request_date desc'],
    unique: false,
    where: null,
  },
  {
    name: 'ix_lu_request_site_unit',
    table: 'lu_request',
    columns: ['site_id', 'equipment_unit_id', 'status'],
    unique: false,
    where: null,
  },
  {
    name: 'ix_lu_request_site_priority',
    table: 'lu_request',
    columns: ['site_id', 'priority', 'request_date desc'],
    unique: false,
    where: null,
  },
  {
    name: 'ux_lu_request_active_technical_management_unit',
    table: 'lu_request',
    columns: ['site_id', 'management_id', 'equipment_unit_id'],
    unique: true,
    where: normalizeCheckDefinition('equipment_unit_id IS NOT NULL AND type = 1 AND status <> 99'),
  },
];

const luRequestEquipmentUnitColumns: readonly ColumnSpec[] = [
  identityBigint('lu_request_equipment_unit_id_seq'),
  uuidNotNull('site_id'),
  bigint('request_id', false, null),
  bigint('equipment_unit_id', false, null),
  bool('is_legacy_primary', false, normalizeDefault('false')),
  bool('is_active', false, normalizeDefault('true')),
  timestamptz('deactivated_at', true, null),
  ...auditTrailColumns(),
];

const luRequestEquipmentUnitIndexes: readonly IndexSpec[] = [
  pkIndex('lu_request_equipment_unit'),
  {
    // CONSTRAINT ux_lu_request_unit UNIQUE (site_id, request_id, equipment_unit_id).
    name: 'ux_lu_request_unit',
    table: 'lu_request_equipment_unit',
    columns: ['site_id', 'request_id', 'equipment_unit_id'],
    unique: true,
    where: null,
  },
  {
    name: 'ix_lu_request_unit_site_request',
    table: 'lu_request_equipment_unit',
    columns: ['site_id', 'request_id', 'is_active'],
    unique: false,
    where: null,
  },
];

// ---------------------------------------------------------------------------
// tenant 0009 — maintenances
// ---------------------------------------------------------------------------

const luMaintenanceColumns: readonly ColumnSpec[] = [
  identityBigint('lu_maintenance_id_seq'),
  uuidNotNull('site_id'),
  bigint('equipment_unit_id', false, null),
  int4('maintenance_type', false, normalizeDefault('99')),
  bigint('management_id', false, null),
  int4('service_type', false, normalizeDefault('0')),
  varchar('institutional_code', 50, true, null),
  bigint('technician_id', true, null),
  bigint('request_id', true, null),
  dateColumn('scheduled_date', true, null),
  timestamptz('start_date', true, null),
  timestamptz('end_date', true, null),
  varchar('description', 2000, true, null),
  int4('status', false, normalizeDefault('0')),
  int4('completion_percentage', false, normalizeDefault('0')),
  bool('step1_cleaning', false, normalizeDefault('false')),
  bool('step2_calibration', false, normalizeDefault('false')),
  bool('step3_testing', false, normalizeDefault('false')),
  bool('step4_final_review', false, normalizeDefault('false')),
  numericColumn('estimated_cost', true, null),
  numericColumn('actual_cost', true, null),
  varchar('recommendations', 1000, true, null),
  dateColumn('suggested_next_maintenance_date', true, null),
  int4('satisfaction_level', true, null),
  varchar('observations', 1000, true, null),
  varchar('historical_source_key', 200, true, null),
  bigint('import_batch_id', true, null),
  ...auditTrailColumns(),
  bigint('row_version', false, normalizeDefault('0')),
];

const luMaintenanceChecks: readonly CheckSpec[] = checks(
  'maintenance_type IN (1, 2, 3, 4, 5, 99)',
  'service_type IN (0, 1)',
  'status IN (0, 1, 2, 3, 99)',
  // completion_percentage BETWEEN 0 AND 100 (deparsed).
  'completion_percentage >= 0 and completion_percentage <= 100',
  '(estimated_cost IS NULL OR estimated_cost >= 0) AND (actual_cost IS NULL OR actual_cost >= 0)',
  // satisfaction_level BETWEEN 1 AND 5 (deparsed).
  'satisfaction_level IS NULL OR (satisfaction_level >= 1 and satisfaction_level <= 5)',
);

const luMaintenanceIndexes: readonly IndexSpec[] = [
  pkIndex('lu_maintenance'),
  {
    name: 'ix_lu_maintenance_site_management_status',
    table: 'lu_maintenance',
    columns: ['site_id', 'management_id', 'status', 'scheduled_date'],
    unique: false,
    where: null,
  },
  {
    name: 'ix_lu_maintenance_site_unit',
    table: 'lu_maintenance',
    columns: ['site_id', 'equipment_unit_id', 'status'],
    unique: false,
    where: null,
  },
  {
    name: 'ux_lu_maintenance_active_plan_unit',
    table: 'lu_maintenance',
    columns: ['site_id', 'management_id', 'equipment_unit_id'],
    unique: true,
    where: normalizeCheckDefinition('status <> 99'),
  },
];

const luMaintenanceTaskColumns: readonly ColumnSpec[] = [
  identityBigint('lu_maintenance_task_id_seq'),
  uuidNotNull('site_id'),
  bigint('maintenance_id', false, null),
  varchar('description', 255, false, null),
  bool('is_completed', false, normalizeDefault('false')),
  bool('is_deleted', false, normalizeDefault('false')),
  timestamptz('created_at', false, timestampDefault),
  timestamptz('updated_at', true, null),
];

const luMaintenanceTaskChecks: readonly CheckSpec[] = checks('length(btrim(description)) > 0');

const luMaintenanceTaskIndexes: readonly IndexSpec[] = [
  pkIndex('lu_maintenance_task'),
  {
    name: 'ix_lu_maintenance_task_site_parent',
    table: 'lu_maintenance_task',
    columns: ['site_id', 'maintenance_id', 'is_deleted'],
    unique: false,
    where: null,
  },
];

const luMaintenanceParticipantColumns: readonly ColumnSpec[] = [
  identityBigint('lu_maintenance_participant_id_seq'),
  uuidNotNull('site_id'),
  bigint('maintenance_id', false, null),
  bigint('person_id', false, null),
  int4('role', false, normalizeDefault('1')),
  bool('is_primary', false, normalizeDefault('false')),
  bool('is_active', false, normalizeDefault('true')),
  timestamptz('assigned_at', false, timestampDefault),
  timestamptz('unassigned_at', true, null),
];

const luMaintenanceParticipantChecks: readonly CheckSpec[] = checks(
  // role BETWEEN 1 AND 4 (deparsed).
  'role >= 1 and role <= 4',
);

const luMaintenanceParticipantIndexes: readonly IndexSpec[] = [
  pkIndex('lu_maintenance_participant'),
  {
    name: 'ix_lu_maintenance_participant_site_parent',
    table: 'lu_maintenance_participant',
    columns: ['site_id', 'maintenance_id', 'is_active'],
    unique: false,
    where: null,
  },
];

const luMaintenanceRequestColumns: readonly ColumnSpec[] = [
  identityBigint('lu_maintenance_request_id_seq'),
  uuidNotNull('site_id'),
  bigint('maintenance_id', false, null),
  bigint('request_id', false, null),
  bool('is_legacy_primary', false, normalizeDefault('false')),
  bool('is_active', false, normalizeDefault('true')),
  timestamptz('deactivated_at', true, null),
  ...auditTrailColumns(),
];

const luMaintenanceRequestIndexes: readonly IndexSpec[] = [
  pkIndex('lu_maintenance_request'),
  {
    // CONSTRAINT ux_lu_maintenance_request UNIQUE (site_id, maintenance_id, request_id).
    name: 'ux_lu_maintenance_request',
    table: 'lu_maintenance_request',
    columns: ['site_id', 'maintenance_id', 'request_id'],
    unique: true,
    where: null,
  },
];

const luMaintenanceCostColumns: readonly ColumnSpec[] = [
  identityBigint('lu_maintenance_cost_id_seq'),
  uuidNotNull('site_id'),
  bigint('maintenance_id', false, null),
  varchar('concept', 200, false, null),
  varchar('description', 500, true, null),
  numericColumn('quantity', false, normalizeDefault('1')),
  varchar('unit_of_measure', 50, true, null),
  numericColumn('unit_price', false, normalizeDefault('0')),
  int4('category', false, normalizeDefault('1')),
  varchar('provider', 200, true, null),
  dateColumn('cost_date', true, null),
  varchar('invoice_number', 100, true, null),
  bool('is_deleted', false, normalizeDefault('false')),
  ...auditTrailColumns(),
];

const luMaintenanceCostChecks: readonly CheckSpec[] = checks(
  'quantity > 0 AND unit_price >= 0',
  'length(btrim(concept)) > 0',
);

const luMaintenanceCostIndexes: readonly IndexSpec[] = [
  pkIndex('lu_maintenance_cost'),
  {
    name: 'ix_lu_maintenance_cost_site_parent',
    table: 'lu_maintenance_cost',
    columns: ['site_id', 'maintenance_id', 'is_deleted'],
    unique: false,
    where: null,
  },
];

// ---------------------------------------------------------------------------
// tenant 0010 — departures
// ---------------------------------------------------------------------------

const luDepartureColumns: readonly ColumnSpec[] = [
  identityBigint('lu_departure_id_seq'),
  uuidNotNull('site_id'),
  bigint('management_id', false, null),
  bigint('equipment_unit_id', true, null),
  bigint('borrower_id', true, null),
  bigint('origin_laboratory_id', true, null),
  varchar('destination', 200, true, null),
  varchar('historical_source_key', 200, true, null),
  bigint('import_batch_id', true, null),
  int4('type', false, normalizeDefault('2')),
  dateColumn('departure_date', false, currentDateDefault),
  dateColumn('estimated_return_date', true, null),
  timestamptz('actual_return_date', true, null),
  varchar('departure_observations', 500, true, null),
  varchar('return_observations', 500, true, null),
  int4('status', false, normalizeDefault('0')),
  ...auditTrailColumns(),
  bigint('row_version', false, normalizeDefault('0')),
];

const luDepartureChecks: readonly CheckSpec[] = checks(
  'type IN (1, 2, 3, 4, 5)',
  'status IN (0, 1, 2, 99)',
);

const luDepartureIndexes: readonly IndexSpec[] = [
  pkIndex('lu_departure'),
  {
    name: 'ix_lu_departure_site_management_status',
    table: 'lu_departure',
    columns: ['site_id', 'management_id', 'status', 'departure_date desc'],
    unique: false,
    where: null,
  },
  {
    name: 'ix_lu_departure_site_unit',
    table: 'lu_departure',
    columns: ['site_id', 'equipment_unit_id', 'status'],
    unique: false,
    where: null,
  },
];

const luDepartureItemColumns: readonly ColumnSpec[] = [
  identityBigint('lu_departure_item_id_seq'),
  uuidNotNull('site_id'),
  bigint('departure_id', false, null),
  bigint('equipment_unit_id', true, null),
  bigint('article_id', true, null),
  varchar('product_name', 200, true, null),
  int4('quantity', true, null),
  // varchar literal default keeps its ::character varying cast.
  varchar('unit_of_measure', 50, true, normalizeDefault("'UNIDAD'::character varying")),
  int4('returned_quantity', true, null),
  varchar('observations', 500, true, null),
  bool('is_removed', false, normalizeDefault('false')),
  ...auditTrailColumns(),
];

const luDepartureItemChecks: readonly CheckSpec[] = checks(
  'quantity IS NULL OR quantity > 0',
  'returned_quantity IS NULL OR returned_quantity >= 0',
);

const luDepartureItemIndexes: readonly IndexSpec[] = [
  pkIndex('lu_departure_item'),
  {
    name: 'ix_lu_departure_item_site_parent',
    table: 'lu_departure_item',
    columns: ['site_id', 'departure_id', 'is_removed'],
    unique: false,
    where: null,
  },
];

// ---------------------------------------------------------------------------
// tenant 0011 — acquisition (request) costs
// ---------------------------------------------------------------------------

const luRequestCostColumns: readonly ColumnSpec[] = [
  identityBigint('lu_request_cost_id_seq'),
  uuidNotNull('site_id'),
  bigint('request_id', false, null),
  varchar('concept', 200, false, null),
  varchar('description', 500, true, null),
  numericColumn('quantity', false, normalizeDefault('1')),
  varchar('unit_of_measure', 50, true, null),
  numericColumn('unit_price', false, normalizeDefault('0')),
  int4('category', false, normalizeDefault('1')),
  varchar('provider', 200, true, null),
  dateColumn('cost_date', true, null),
  varchar('invoice_number', 100, true, null),
  bool('is_deleted', false, normalizeDefault('false')),
  ...auditTrailColumns(),
];

const luRequestCostChecks: readonly CheckSpec[] = checks(
  'quantity > 0 AND unit_price >= 0',
  'length(btrim(concept)) > 0',
);

const luRequestCostIndexes: readonly IndexSpec[] = [
  pkIndex('lu_request_cost'),
  {
    name: 'ix_lu_request_cost_site_parent',
    table: 'lu_request_cost',
    columns: ['site_id', 'request_id', 'is_deleted'],
    unique: false,
    where: null,
  },
];

// ---------------------------------------------------------------------------
// tenant 0012 — people
// ---------------------------------------------------------------------------

const luPersonColumns: readonly ColumnSpec[] = [
  identityBigint('lu_person_id_seq'),
  uuidNotNull('site_id'),
  varchar('actor_code', 30, true, null),
  varchar('person_type', 20, false, normalizeDefault("'internal'::character varying")),
  varchar('name', 200, false, null),
  varchar('email', 100, true, null),
  varchar('phone_number', 20, true, null),
  bool('is_entity', false, normalizeDefault('false')),
  varchar('address', 500, true, null),
  int4('category', false, normalizeDefault('99')),
  int4('status', false, normalizeDefault('0')),
  ...auditTrailColumns(),
];

const luPersonChecks: readonly CheckSpec[] = checks(
  "person_type IN ('internal', 'external')",
  'category IN (1, 2, 3, 4, 5, 99)',
  'status IN (0, 1, 2)',
  'length(btrim(name)) > 0',
  "person_type <> 'external' OR length(btrim(coalesce(address, ''))) > 0",
);

const luPersonIndexes: readonly IndexSpec[] = [
  pkIndex('lu_person'),
  {
    name: 'ux_lu_person_site_actor_code',
    table: 'lu_person',
    columns: ['site_id', 'lower(actor_code)'],
    unique: true,
    where: normalizeCheckDefinition('actor_code IS NOT NULL AND status <> 2'),
  },
  {
    name: 'ix_lu_person_site_status_type',
    table: 'lu_person',
    columns: ['site_id', 'status', 'person_type', 'lower(name)'],
    unique: false,
    where: null,
  },
  {
    name: 'ix_lu_person_site_email',
    table: 'lu_person',
    columns: ['site_id', 'lower(email)'],
    unique: false,
    where: null,
  },
];

// ---------------------------------------------------------------------------
// tenant 0013 — migration history (structurally identical to the
// control-plane 0006 lu_migration_history; duplicated here to keep this
// module free of runtime imports from schema-manifest-f2.ts, which re-exports
// this module).
// ---------------------------------------------------------------------------

const luMigrationHistoryTable: TableManifest = {
  columns: [
    {
      name: 'stream',
      dataType: 'text',
      udtName: 'text',
      charMaxLength: null,
      isNullable: false,
      columnDefault: null,
    },
    int4('ordinal', false, null),
    {
      name: 'relative_path',
      dataType: 'text',
      udtName: 'text',
      charMaxLength: null,
      isNullable: false,
      columnDefault: null,
    },
    char('sha256', 64, false, null),
    int4('bytes', false, null),
    {
      name: 'work_id',
      dataType: 'text',
      udtName: 'text',
      charMaxLength: null,
      isNullable: true,
      columnDefault: null,
    },
    timestamptz('applied_at', false, timestampDefault),
  ],
  primaryKey: { columns: ['stream', 'ordinal'] },
  uniques: [{ columns: ['stream', 'relative_path'] }],
  foreignKeys: [],
  checks: checks(
    "stream IN ('control-plane', 'tenant')",
    'ordinal >= 1',
    "sha256 ~ '^[0-9a-f]{64}$'",
    'bytes > 0',
    'length(relative_path) > 0',
  ),
  indexes: [
    pkIndex('lu_migration_history', ['stream', 'ordinal']),
    {
      name: 'lu_migration_history_stream_relative_path_key',
      table: 'lu_migration_history',
      columns: ['stream', 'relative_path'],
      unique: true,
      where: null,
    },
    {
      name: 'ix_lu_migration_history_applied_at',
      table: 'lu_migration_history',
      columns: ['applied_at'],
      unique: false,
      where: null,
    },
  ],
};

// ---------------------------------------------------------------------------
// Final tenant table set (post 0013)
// ---------------------------------------------------------------------------

export type TenantFinalTable =
  | 'lu_management'
  | 'lu_laboratory'
  | 'lu_equipment'
  | 'lu_equipment_unit'
  | 'lu_management_plan'
  | 'lu_notification'
  | 'lu_country'
  | 'lu_city'
  | 'lu_equipment_note'
  | 'lu_equipment_unit_state_history'
  | 'lu_verification_check_item'
  | 'lu_verification'
  | 'lu_verification_check_result'
  | 'lu_verification_fault'
  | 'lu_request'
  | 'lu_request_equipment_unit'
  | 'lu_maintenance'
  | 'lu_maintenance_task'
  | 'lu_maintenance_participant'
  | 'lu_maintenance_request'
  | 'lu_maintenance_cost'
  | 'lu_departure'
  | 'lu_departure_item'
  | 'lu_request_cost'
  | 'lu_person'
  | 'lu_migration_history';

/**
 * Exact tenant table-name list for final status inspection after 0013
 * (25 operational tables created by 0001-0012 + lu_migration_history from
 * 0013 = 26). Only tables the tenant SQL actually creates are listed.
 */
export const TENANT_FINAL_TABLES: readonly TenantFinalTable[] = [
  'lu_management',
  'lu_laboratory',
  'lu_equipment',
  'lu_equipment_unit',
  'lu_management_plan',
  'lu_notification',
  'lu_country',
  'lu_city',
  'lu_equipment_note',
  'lu_equipment_unit_state_history',
  'lu_verification_check_item',
  'lu_verification',
  'lu_verification_check_result',
  'lu_verification_fault',
  'lu_request',
  'lu_request_equipment_unit',
  'lu_maintenance',
  'lu_maintenance_task',
  'lu_maintenance_participant',
  'lu_maintenance_request',
  'lu_maintenance_cost',
  'lu_departure',
  'lu_departure_item',
  'lu_request_cost',
  'lu_person',
  'lu_migration_history',
];

/**
 * Exhaustive tenant schema expected after tenant migrations 0001..0013.
 * Uses the FINAL variants of the tables later migrations extend
 * (lu_laboratory with 0003's indexes, lu_equipment with 0004's indexes,
 * lu_equipment_unit with 0005's CHECKs/index). Every table is complete:
 * exact columns, defaults, PK, uniques, FKs, checks and indexes.
 */
export const TENANT_FINAL_SCHEMA_MANIFEST: SchemaManifest<TenantFinalTable> = {
  schema: 'public',
  tables: {
    lu_management: {
      columns: luManagementColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luManagementChecks,
      indexes: luManagementIndexes,
    },
    lu_laboratory: {
      columns: luLaboratoryColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luLaboratoryChecks,
      indexes: luLaboratoryFinalIndexes,
    },
    lu_equipment: {
      columns: luEquipmentColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luEquipmentChecks,
      indexes: luEquipmentFinalIndexes,
    },
    lu_equipment_unit: {
      columns: luEquipmentUnitColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luEquipmentUnitFinalChecks,
      indexes: luEquipmentUnitFinalIndexes,
    },
    lu_management_plan: {
      columns: luManagementPlanColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luManagementPlanChecks,
      indexes: luManagementPlanIndexes,
    },
    lu_notification: {
      columns: luNotificationColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luNotificationChecks,
      indexes: luNotificationIndexes,
    },
    lu_country: {
      columns: luCountryColumns,
      primaryKey: { columns: ['id'] },
      uniques: [{ columns: ['site_id', 'id'] }],
      foreignKeys: [],
      checks: luCountryChecks,
      indexes: luCountryIndexes,
    },
    lu_city: {
      columns: luCityColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: luCityForeignKeys,
      checks: luCityChecks,
      indexes: luCityIndexes,
    },
    lu_equipment_note: {
      columns: luEquipmentNoteColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: luEquipmentNoteForeignKeys,
      checks: [],
      indexes: luEquipmentNoteIndexes,
    },
    lu_equipment_unit_state_history: {
      columns: luEquipmentUnitStateHistoryColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luEquipmentUnitStateHistoryChecks,
      indexes: luEquipmentUnitStateHistoryIndexes,
    },
    lu_verification_check_item: {
      columns: luVerificationCheckItemColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: [],
      indexes: [pkIndex('lu_verification_check_item')],
    },
    lu_verification: {
      columns: luVerificationColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luVerificationChecks,
      indexes: luVerificationIndexes,
    },
    lu_verification_check_result: {
      columns: luVerificationCheckResultColumns,
      primaryKey: { columns: ['id'] },
      uniques: [{ columns: ['verification_id', 'check_item_id'] }],
      foreignKeys: [],
      checks: luVerificationCheckResultChecks,
      indexes: luVerificationCheckResultIndexes,
    },
    lu_verification_fault: {
      columns: luVerificationFaultColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: [],
      indexes: luVerificationFaultIndexes,
    },
    lu_request: {
      columns: luRequestColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luRequestChecks,
      indexes: luRequestIndexes,
    },
    lu_request_equipment_unit: {
      columns: luRequestEquipmentUnitColumns,
      primaryKey: { columns: ['id'] },
      uniques: [{ columns: ['site_id', 'request_id', 'equipment_unit_id'] }],
      foreignKeys: [],
      checks: [],
      indexes: luRequestEquipmentUnitIndexes,
    },
    lu_maintenance: {
      columns: luMaintenanceColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luMaintenanceChecks,
      indexes: luMaintenanceIndexes,
    },
    lu_maintenance_task: {
      columns: luMaintenanceTaskColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luMaintenanceTaskChecks,
      indexes: luMaintenanceTaskIndexes,
    },
    lu_maintenance_participant: {
      columns: luMaintenanceParticipantColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luMaintenanceParticipantChecks,
      indexes: luMaintenanceParticipantIndexes,
    },
    lu_maintenance_request: {
      columns: luMaintenanceRequestColumns,
      primaryKey: { columns: ['id'] },
      uniques: [{ columns: ['site_id', 'maintenance_id', 'request_id'] }],
      foreignKeys: [],
      checks: [],
      indexes: luMaintenanceRequestIndexes,
    },
    lu_maintenance_cost: {
      columns: luMaintenanceCostColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luMaintenanceCostChecks,
      indexes: luMaintenanceCostIndexes,
    },
    lu_departure: {
      columns: luDepartureColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luDepartureChecks,
      indexes: luDepartureIndexes,
    },
    lu_departure_item: {
      columns: luDepartureItemColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luDepartureItemChecks,
      indexes: luDepartureItemIndexes,
    },
    lu_request_cost: {
      columns: luRequestCostColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luRequestCostChecks,
      indexes: luRequestCostIndexes,
    },
    lu_person: {
      columns: luPersonColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luPersonChecks,
      indexes: luPersonIndexes,
    },
    lu_migration_history: luMigrationHistoryTable,
  },
};

// ---------------------------------------------------------------------------
// Per-ordinal postcondition manifests (immutable 0001-0012 + current 0013)
// ---------------------------------------------------------------------------

export type TenantOrdinal = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13;

export interface TenantMigrationManifest {
  readonly ordinal: TenantOrdinal;
  readonly relativePath: string;
  /**
   * Exact postcondition manifest for the tables this migration creates or
   * alters. null when the migration is ACL-only (tenant 0006): its
   * postcondition is carried exclusively by `supplemental`.
   */
  readonly schemaManifest: SchemaManifest<string> | null;
  readonly supplemental: MigrationSupplementalExpectation;
}

const TENANT_RELATIVE_PATHS = {
  1: 'tenant/0001_dashboard_foundation.sql',
  2: 'tenant/0002_catalogs.sql',
  3: 'tenant/0003_academic_laboratories.sql',
  4: 'tenant/0004_equipment_notes.sql',
  5: 'tenant/0005_equipment_units_history.sql',
  6: 'tenant/0006_management_operations.sql',
  7: 'tenant/0007_verifications.sql',
  8: 'tenant/0008_requests.sql',
  9: 'tenant/0009_maintenances.sql',
  10: 'tenant/0010_departures.sql',
  11: 'tenant/0011_acquisition_costs.sql',
  12: 'tenant/0012_people.sql',
  13: 'tenant/0013_migration_history.sql',
} as const;

// --- Supplemental expectations per ordinal ----------------------------------

const tenantSupplemental0001: MigrationSupplementalExpectation = {
  stream: 'tenant',
  relativePath: TENANT_RELATIVE_PATHS[1],
  sequences: [
    {
      name: 'lu_management_id_seq',
      ownedByTable: 'lu_management',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
    {
      name: 'lu_laboratory_id_seq',
      ownedByTable: 'lu_laboratory',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
    {
      name: 'lu_equipment_id_seq',
      ownedByTable: 'lu_equipment',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
    {
      name: 'lu_equipment_unit_id_seq',
      ownedByTable: 'lu_equipment_unit',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
    {
      name: 'lu_management_plan_id_seq',
      ownedByTable: 'lu_management_plan',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
    {
      name: 'lu_notification_id_seq',
      ownedByTable: 'lu_notification',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
  ],
  triggers: [],
  tableAcls: [
    {
      role: 'lu_auth_runtime',
      table: 'lu_management',
      grants: [{ privilege: 'SELECT', columns: null, granted: true }],
    },
    {
      role: 'lu_auth_runtime',
      table: 'lu_laboratory',
      grants: [{ privilege: 'SELECT', columns: null, granted: true }],
    },
    {
      role: 'lu_auth_runtime',
      table: 'lu_equipment',
      grants: [{ privilege: 'SELECT', columns: null, granted: true }],
    },
    {
      role: 'lu_auth_runtime',
      table: 'lu_equipment_unit',
      grants: [{ privilege: 'SELECT', columns: null, granted: true }],
    },
    {
      role: 'lu_auth_runtime',
      table: 'lu_management_plan',
      grants: [{ privilege: 'SELECT', columns: null, granted: true }],
    },
    {
      role: 'lu_auth_runtime',
      table: 'lu_notification',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: ['is_read'], granted: true },
      ],
    },
  ],
  sequenceAcls: [],
  functionAcls: [],
  schemaAcls: [{ role: 'lu_auth_runtime', schema: 'public', privilege: 'USAGE', granted: true }],
  notes: ['All grants are role-guarded (apply only when lu_auth_runtime existed at apply time).'],
};

const tenantSupplemental0002: MigrationSupplementalExpectation = {
  stream: 'tenant',
  relativePath: TENANT_RELATIVE_PATHS[2],
  sequences: [
    {
      name: 'lu_country_id_seq',
      ownedByTable: 'lu_country',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
    {
      name: 'lu_city_id_seq',
      ownedByTable: 'lu_city',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
  ],
  triggers: [],
  tableAcls: [
    {
      role: 'lu_auth_runtime',
      table: 'lu_country',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
      ],
    },
    {
      role: 'lu_auth_runtime',
      table: 'lu_city',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
      ],
    },
  ],
  sequenceAcls: [
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_country_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_city_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
  ],
  functionAcls: [],
  schemaAcls: [{ role: 'lu_auth_runtime', schema: 'public', privilege: 'USAGE', granted: true }],
  notes: ['Role-guarded grant block.'],
};

const tenantSupplemental0003: MigrationSupplementalExpectation = {
  stream: 'tenant',
  relativePath: TENANT_RELATIVE_PATHS[3],
  sequences: [],
  triggers: [],
  tableAcls: [
    {
      role: 'lu_auth_runtime',
      table: 'lu_laboratory',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
      ],
    },
  ],
  sequenceAcls: [
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_laboratory_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
  ],
  functionAcls: [],
  schemaAcls: [],
  notes: [
    '0003 does not create lu_laboratory: its CREATE TABLE IF NOT EXISTS is a no-op because 0001 already created the table. Only the three indexes are new.',
    'Role-guarded grant block.',
  ],
};

const tenantSupplemental0004: MigrationSupplementalExpectation = {
  stream: 'tenant',
  relativePath: TENANT_RELATIVE_PATHS[4],
  sequences: [
    {
      name: 'lu_equipment_note_id_seq',
      ownedByTable: 'lu_equipment_note',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
  ],
  triggers: [],
  tableAcls: [
    {
      role: 'lu_auth_runtime',
      table: 'lu_equipment',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
      ],
    },
    {
      role: 'lu_auth_runtime',
      table: 'lu_equipment_note',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
        { privilege: 'DELETE', columns: null, granted: true },
      ],
    },
  ],
  sequenceAcls: [
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_equipment_note_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
  ],
  functionAcls: [],
  schemaAcls: [],
  notes: ['Role-guarded grant block.'],
};

const tenantSupplemental0005: MigrationSupplementalExpectation = {
  stream: 'tenant',
  relativePath: TENANT_RELATIVE_PATHS[5],
  sequences: [
    {
      name: 'lu_equipment_unit_state_history_id_seq',
      ownedByTable: 'lu_equipment_unit_state_history',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
  ],
  triggers: [],
  tableAcls: [
    {
      role: 'lu_auth_runtime',
      table: 'lu_equipment_unit',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
      ],
    },
    {
      role: 'lu_auth_runtime',
      table: 'lu_equipment_unit_state_history',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
      ],
    },
  ],
  sequenceAcls: [
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_equipment_unit_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_equipment_unit_state_history_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
  ],
  functionAcls: [],
  schemaAcls: [],
  notes: [
    'The two added lu_equipment_unit CHECKs are installed via role-guarded DO blocks.',
    'Role-guarded grant block.',
  ],
};

const tenantSupplemental0006: MigrationSupplementalExpectation = {
  stream: 'tenant',
  relativePath: TENANT_RELATIVE_PATHS[6],
  sequences: [],
  triggers: [],
  tableAcls: [
    {
      role: 'lu_auth_runtime',
      table: 'lu_management',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
      ],
    },
    {
      role: 'lu_auth_runtime',
      table: 'lu_management_plan',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
      ],
    },
  ],
  sequenceAcls: [
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_management_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_management_plan_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
  ],
  functionAcls: [],
  schemaAcls: [],
  notes: [
    'Tenant 0006 is ACL-only: it mutates no schema surface and therefore has NO SchemaManifest.',
  ],
};

const tenantSupplemental0007: MigrationSupplementalExpectation = {
  stream: 'tenant',
  relativePath: TENANT_RELATIVE_PATHS[7],
  sequences: [
    {
      name: 'lu_verification_check_item_id_seq',
      ownedByTable: 'lu_verification_check_item',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
    {
      name: 'lu_verification_id_seq',
      ownedByTable: 'lu_verification',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
    {
      name: 'lu_verification_check_result_id_seq',
      ownedByTable: 'lu_verification_check_result',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
    {
      name: 'lu_verification_fault_id_seq',
      ownedByTable: 'lu_verification_fault',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
  ],
  triggers: [],
  tableAcls: [
    {
      role: 'lu_auth_runtime',
      table: 'lu_verification_check_item',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
      ],
    },
    {
      role: 'lu_auth_runtime',
      table: 'lu_verification',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
      ],
    },
    {
      role: 'lu_auth_runtime',
      table: 'lu_verification_check_result',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
        { privilege: 'DELETE', columns: null, granted: true },
      ],
    },
    {
      role: 'lu_auth_runtime',
      table: 'lu_verification_fault',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
      ],
    },
  ],
  sequenceAcls: [
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_verification_check_item_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_verification_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_verification_check_result_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_verification_fault_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
  ],
  functionAcls: [],
  schemaAcls: [],
  notes: ['Role-guarded grant block.'],
};

const tenantSupplemental0008: MigrationSupplementalExpectation = {
  stream: 'tenant',
  relativePath: TENANT_RELATIVE_PATHS[8],
  sequences: [
    {
      name: 'lu_request_id_seq',
      ownedByTable: 'lu_request',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
    {
      name: 'lu_request_equipment_unit_id_seq',
      ownedByTable: 'lu_request_equipment_unit',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
  ],
  triggers: [],
  tableAcls: [
    {
      role: 'lu_auth_runtime',
      table: 'lu_request',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
      ],
    },
    {
      role: 'lu_auth_runtime',
      table: 'lu_request_equipment_unit',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
        { privilege: 'DELETE', columns: null, granted: true },
      ],
    },
  ],
  sequenceAcls: [
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_request_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_request_equipment_unit_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
  ],
  functionAcls: [],
  schemaAcls: [],
  notes: ['Role-guarded grant block.'],
};

const tenantSupplemental0009: MigrationSupplementalExpectation = {
  stream: 'tenant',
  relativePath: TENANT_RELATIVE_PATHS[9],
  sequences: [
    {
      name: 'lu_maintenance_id_seq',
      ownedByTable: 'lu_maintenance',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
    {
      name: 'lu_maintenance_task_id_seq',
      ownedByTable: 'lu_maintenance_task',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
    {
      name: 'lu_maintenance_participant_id_seq',
      ownedByTable: 'lu_maintenance_participant',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
    {
      name: 'lu_maintenance_request_id_seq',
      ownedByTable: 'lu_maintenance_request',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
    {
      name: 'lu_maintenance_cost_id_seq',
      ownedByTable: 'lu_maintenance_cost',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
  ],
  triggers: [],
  tableAcls: [
    {
      role: 'lu_auth_runtime',
      table: 'lu_maintenance',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
      ],
    },
    {
      role: 'lu_auth_runtime',
      table: 'lu_maintenance_task',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
        { privilege: 'DELETE', columns: null, granted: true },
      ],
    },
    {
      role: 'lu_auth_runtime',
      table: 'lu_maintenance_participant',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
      ],
    },
    {
      role: 'lu_auth_runtime',
      table: 'lu_maintenance_request',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
        { privilege: 'DELETE', columns: null, granted: true },
      ],
    },
    {
      role: 'lu_auth_runtime',
      table: 'lu_maintenance_cost',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
      ],
    },
  ],
  sequenceAcls: [
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_maintenance_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_maintenance_task_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_maintenance_participant_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_maintenance_request_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_maintenance_cost_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
  ],
  functionAcls: [],
  schemaAcls: [],
  notes: ['Role-guarded grant block.'],
};

const tenantSupplemental0010: MigrationSupplementalExpectation = {
  stream: 'tenant',
  relativePath: TENANT_RELATIVE_PATHS[10],
  sequences: [
    {
      name: 'lu_departure_id_seq',
      ownedByTable: 'lu_departure',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
    {
      name: 'lu_departure_item_id_seq',
      ownedByTable: 'lu_departure_item',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
  ],
  triggers: [],
  tableAcls: [
    {
      role: 'lu_auth_runtime',
      table: 'lu_departure',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
      ],
    },
    {
      role: 'lu_auth_runtime',
      table: 'lu_departure_item',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
        { privilege: 'DELETE', columns: null, granted: true },
      ],
    },
  ],
  sequenceAcls: [
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_departure_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_departure_item_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
  ],
  functionAcls: [],
  schemaAcls: [],
  notes: ['Role-guarded grant block.'],
};

const tenantSupplemental0011: MigrationSupplementalExpectation = {
  stream: 'tenant',
  relativePath: TENANT_RELATIVE_PATHS[11],
  sequences: [
    {
      name: 'lu_request_cost_id_seq',
      ownedByTable: 'lu_request_cost',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
  ],
  triggers: [],
  tableAcls: [
    {
      role: 'lu_auth_runtime',
      table: 'lu_request_cost',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
        { privilege: 'DELETE', columns: null, granted: true },
      ],
    },
  ],
  sequenceAcls: [
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_request_cost_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
  ],
  functionAcls: [],
  schemaAcls: [],
  notes: ['Role-guarded grant block.'],
};

const tenantSupplemental0012: MigrationSupplementalExpectation = {
  stream: 'tenant',
  relativePath: TENANT_RELATIVE_PATHS[12],
  sequences: [
    {
      name: 'lu_person_id_seq',
      ownedByTable: 'lu_person',
      ownedByColumn: 'id',
      identity: 'BY DEFAULT',
    },
  ],
  triggers: [],
  tableAcls: [
    {
      role: 'lu_auth_runtime',
      table: 'lu_person',
      grants: [
        { privilege: 'SELECT', columns: null, granted: true },
        { privilege: 'INSERT', columns: null, granted: true },
        { privilege: 'UPDATE', columns: null, granted: true },
      ],
    },
  ],
  sequenceAcls: [
    {
      role: 'lu_auth_runtime',
      sequence: 'lu_person_id_seq',
      privileges: ['USAGE', 'SELECT', 'UPDATE'],
      granted: true,
    },
  ],
  functionAcls: [],
  schemaAcls: [],
  notes: ['Role-guarded grant block.'],
};

const tenantSupplemental0013: MigrationSupplementalExpectation = {
  stream: 'tenant',
  relativePath: TENANT_RELATIVE_PATHS[13],
  sequences: [],
  triggers: [
    {
      table: 'lu_migration_history',
      name: 'trg_lu_migration_history_no_update',
      timing: 'BEFORE',
      events: ['UPDATE'],
      updateColumns: null,
      isConstraintTrigger: false,
      deferrable: false,
      initiallyDeferred: false,
      functionName: 'lu_migration_history_immutable()',
    },
    {
      table: 'lu_migration_history',
      name: 'trg_lu_migration_history_no_delete',
      timing: 'BEFORE',
      events: ['DELETE'],
      updateColumns: null,
      isConstraintTrigger: false,
      deferrable: false,
      initiallyDeferred: false,
      functionName: 'lu_migration_history_immutable()',
    },
  ],
  tableAcls: [
    {
      role: 'lu_auth_runtime',
      table: 'lu_migration_history',
      grants: [
        { privilege: 'INSERT', columns: null, granted: false },
        { privilege: 'UPDATE', columns: null, granted: false },
        { privilege: 'DELETE', columns: null, granted: false },
        { privilege: 'TRUNCATE', columns: null, granted: false },
        { privilege: 'SELECT', columns: null, granted: true },
      ],
    },
  ],
  sequenceAcls: [],
  functionAcls: [
    {
      role: 'PUBLIC',
      functionName: 'lu_migration_history_immutable()',
      privilege: 'EXECUTE',
      granted: false,
    },
  ],
  schemaAcls: [],
  notes: [
    'Fail-closed preflight: lu_auth_runtime role must exist before applying 0013.',
    '0013 creates no sequences (composite PK).',
  ],
};

const tenantSupplementalByOrdinal: Readonly<
  Record<TenantOrdinal, MigrationSupplementalExpectation>
> = {
  1: tenantSupplemental0001,
  2: tenantSupplemental0002,
  3: tenantSupplemental0003,
  4: tenantSupplemental0004,
  5: tenantSupplemental0005,
  6: tenantSupplemental0006,
  7: tenantSupplemental0007,
  8: tenantSupplemental0008,
  9: tenantSupplemental0009,
  10: tenantSupplemental0010,
  11: tenantSupplemental0011,
  12: tenantSupplemental0012,
  13: tenantSupplemental0013,
};

export const TENANT_SUPPLEMENTAL_EXPECTATIONS = tenantSupplementalByOrdinal;

// --- Per-ordinal SchemaManifests --------------------------------------------

const tenantManifest0001: SchemaManifest<string> = {
  schema: 'public',
  tables: {
    lu_management: {
      columns: luManagementColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luManagementChecks,
      indexes: luManagementIndexes,
    },
    lu_laboratory: {
      columns: luLaboratoryColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luLaboratoryChecks,
      indexes: luLaboratory0001Indexes,
    },
    lu_equipment: {
      columns: luEquipmentColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luEquipmentChecks,
      indexes: luEquipment0001Indexes,
    },
    lu_equipment_unit: {
      columns: luEquipmentUnitColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luEquipmentUnit0001Checks,
      indexes: luEquipmentUnit0001Indexes,
    },
    lu_management_plan: {
      columns: luManagementPlanColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luManagementPlanChecks,
      indexes: luManagementPlanIndexes,
    },
    lu_notification: {
      columns: luNotificationColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luNotificationChecks,
      indexes: luNotificationIndexes,
    },
  },
};

const tenantManifest0002: SchemaManifest<string> = {
  schema: 'public',
  tables: {
    lu_country: {
      columns: luCountryColumns,
      primaryKey: { columns: ['id'] },
      uniques: [{ columns: ['site_id', 'id'] }],
      foreignKeys: [],
      checks: luCountryChecks,
      indexes: luCountryIndexes,
    },
    lu_city: {
      columns: luCityColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: luCityForeignKeys,
      checks: luCityChecks,
      indexes: luCityIndexes,
    },
  },
};

/** Post-0003 state of lu_laboratory: 0001 definition plus 0003's three indexes. */
const tenantManifest0003: SchemaManifest<string> = {
  schema: 'public',
  tables: {
    lu_laboratory: {
      columns: luLaboratoryColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luLaboratoryChecks,
      indexes: luLaboratoryFinalIndexes,
    },
  },
};

/** Post-0004 state: lu_equipment with 0004's indexes + the new note table. */
const tenantManifest0004: SchemaManifest<string> = {
  schema: 'public',
  tables: {
    lu_equipment: {
      columns: luEquipmentColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luEquipmentChecks,
      indexes: luEquipmentFinalIndexes,
    },
    lu_equipment_note: {
      columns: luEquipmentNoteColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: luEquipmentNoteForeignKeys,
      checks: [],
      indexes: luEquipmentNoteIndexes,
    },
  },
};

/** Post-0005 state: lu_equipment_unit with 0005's CHECKs/index + history table. */
const tenantManifest0005: SchemaManifest<string> = {
  schema: 'public',
  tables: {
    lu_equipment_unit: {
      columns: luEquipmentUnitColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luEquipmentUnitFinalChecks,
      indexes: luEquipmentUnitFinalIndexes,
    },
    lu_equipment_unit_state_history: {
      columns: luEquipmentUnitStateHistoryColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luEquipmentUnitStateHistoryChecks,
      indexes: luEquipmentUnitStateHistoryIndexes,
    },
  },
};

const tenantManifest0007: SchemaManifest<string> = {
  schema: 'public',
  tables: {
    lu_verification_check_item: {
      columns: luVerificationCheckItemColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: [],
      indexes: [pkIndex('lu_verification_check_item')],
    },
    lu_verification: {
      columns: luVerificationColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luVerificationChecks,
      indexes: luVerificationIndexes,
    },
    lu_verification_check_result: {
      columns: luVerificationCheckResultColumns,
      primaryKey: { columns: ['id'] },
      uniques: [{ columns: ['verification_id', 'check_item_id'] }],
      foreignKeys: [],
      checks: luVerificationCheckResultChecks,
      indexes: luVerificationCheckResultIndexes,
    },
    lu_verification_fault: {
      columns: luVerificationFaultColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: [],
      indexes: luVerificationFaultIndexes,
    },
  },
};

const tenantManifest0008: SchemaManifest<string> = {
  schema: 'public',
  tables: {
    lu_request: {
      columns: luRequestColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luRequestChecks,
      indexes: luRequestIndexes,
    },
    lu_request_equipment_unit: {
      columns: luRequestEquipmentUnitColumns,
      primaryKey: { columns: ['id'] },
      uniques: [{ columns: ['site_id', 'request_id', 'equipment_unit_id'] }],
      foreignKeys: [],
      checks: [],
      indexes: luRequestEquipmentUnitIndexes,
    },
  },
};

const tenantManifest0009: SchemaManifest<string> = {
  schema: 'public',
  tables: {
    lu_maintenance: {
      columns: luMaintenanceColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luMaintenanceChecks,
      indexes: luMaintenanceIndexes,
    },
    lu_maintenance_task: {
      columns: luMaintenanceTaskColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luMaintenanceTaskChecks,
      indexes: luMaintenanceTaskIndexes,
    },
    lu_maintenance_participant: {
      columns: luMaintenanceParticipantColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luMaintenanceParticipantChecks,
      indexes: luMaintenanceParticipantIndexes,
    },
    lu_maintenance_request: {
      columns: luMaintenanceRequestColumns,
      primaryKey: { columns: ['id'] },
      uniques: [{ columns: ['site_id', 'maintenance_id', 'request_id'] }],
      foreignKeys: [],
      checks: [],
      indexes: luMaintenanceRequestIndexes,
    },
    lu_maintenance_cost: {
      columns: luMaintenanceCostColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luMaintenanceCostChecks,
      indexes: luMaintenanceCostIndexes,
    },
  },
};

const tenantManifest0010: SchemaManifest<string> = {
  schema: 'public',
  tables: {
    lu_departure: {
      columns: luDepartureColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luDepartureChecks,
      indexes: luDepartureIndexes,
    },
    lu_departure_item: {
      columns: luDepartureItemColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luDepartureItemChecks,
      indexes: luDepartureItemIndexes,
    },
  },
};

const tenantManifest0011: SchemaManifest<string> = {
  schema: 'public',
  tables: {
    lu_request_cost: {
      columns: luRequestCostColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luRequestCostChecks,
      indexes: luRequestCostIndexes,
    },
  },
};

const tenantManifest0012: SchemaManifest<string> = {
  schema: 'public',
  tables: {
    lu_person: {
      columns: luPersonColumns,
      primaryKey: { columns: ['id'] },
      uniques: [],
      foreignKeys: [],
      checks: luPersonChecks,
      indexes: luPersonIndexes,
    },
  },
};

const tenantManifest0013: SchemaManifest<string> = {
  schema: 'public',
  tables: {
    lu_migration_history: luMigrationHistoryTable,
  },
};

/**
 * Typed lookup (by ordinal) of the exact postcondition manifest for each
 * tenant migration's touched tables. Ordinal 6 is ACL-only and carries a null
 * SchemaManifest; its postcondition lives in TENANT_SUPPLEMENTAL_EXPECTATIONS.
 */
export const TENANT_MIGRATION_MANIFESTS: Readonly<Record<TenantOrdinal, TenantMigrationManifest>> =
  {
    1: {
      ordinal: 1,
      relativePath: TENANT_RELATIVE_PATHS[1],
      schemaManifest: tenantManifest0001,
      supplemental: tenantSupplemental0001,
    },
    2: {
      ordinal: 2,
      relativePath: TENANT_RELATIVE_PATHS[2],
      schemaManifest: tenantManifest0002,
      supplemental: tenantSupplemental0002,
    },
    3: {
      ordinal: 3,
      relativePath: TENANT_RELATIVE_PATHS[3],
      schemaManifest: tenantManifest0003,
      supplemental: tenantSupplemental0003,
    },
    4: {
      ordinal: 4,
      relativePath: TENANT_RELATIVE_PATHS[4],
      schemaManifest: tenantManifest0004,
      supplemental: tenantSupplemental0004,
    },
    5: {
      ordinal: 5,
      relativePath: TENANT_RELATIVE_PATHS[5],
      schemaManifest: tenantManifest0005,
      supplemental: tenantSupplemental0005,
    },
    6: {
      ordinal: 6,
      relativePath: TENANT_RELATIVE_PATHS[6],
      schemaManifest: null,
      supplemental: tenantSupplemental0006,
    },
    7: {
      ordinal: 7,
      relativePath: TENANT_RELATIVE_PATHS[7],
      schemaManifest: tenantManifest0007,
      supplemental: tenantSupplemental0007,
    },
    8: {
      ordinal: 8,
      relativePath: TENANT_RELATIVE_PATHS[8],
      schemaManifest: tenantManifest0008,
      supplemental: tenantSupplemental0008,
    },
    9: {
      ordinal: 9,
      relativePath: TENANT_RELATIVE_PATHS[9],
      schemaManifest: tenantManifest0009,
      supplemental: tenantSupplemental0009,
    },
    10: {
      ordinal: 10,
      relativePath: TENANT_RELATIVE_PATHS[10],
      schemaManifest: tenantManifest0010,
      supplemental: tenantSupplemental0010,
    },
    11: {
      ordinal: 11,
      relativePath: TENANT_RELATIVE_PATHS[11],
      schemaManifest: tenantManifest0011,
      supplemental: tenantSupplemental0011,
    },
    12: {
      ordinal: 12,
      relativePath: TENANT_RELATIVE_PATHS[12],
      schemaManifest: tenantManifest0012,
      supplemental: tenantSupplemental0012,
    },
    13: {
      ordinal: 13,
      relativePath: TENANT_RELATIVE_PATHS[13],
      schemaManifest: tenantManifest0013,
      supplemental: tenantSupplemental0013,
    },
  };
